import("//build_overrides/llvm.gni")

llvm_static_library("wasm") {
  output_name = "lldbPluginObjectFileWasm"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "ObjectFileWasm.cpp" ]
}
