import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("FormatTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "BracesInserterTest.cpp",
    "BracesRemoverTest.cpp",
    "CleanupTest.cpp",
    "ConfigParseTest.cpp",
    "DefinitionBlockSeparatorTest.cpp",
    "FormatReplacementTest.cpp",
    "FormatTest.cpp",
    "FormatTestCSharp.cpp",
    "FormatTestComments.cpp",
    "FormatTestJS.cpp",
    "FormatTestJava.cpp",
    "FormatTestJson.cpp",
    "FormatTestMacroExpansion.cpp",
    "FormatTestObjC.cpp",
    "FormatTestProto.cpp",
    "FormatTestRawStrings.cpp",
    "FormatTestSelective.cpp",
    "FormatTestTableGen.cpp",
    "FormatTestTextProto.cpp",
    "FormatTestVerilog.cpp",
    "FormatTokenSourceTest.cpp",
    "IntegerLiteralSeparatorTest.cpp",
    "MacroCallReconstructorTest.cpp",
    "MacroExpanderTest.cpp",
    "MatchFilePathTest.cpp",
    "NamespaceEndCommentsFixerTest.cpp",
    "ObjCPropertyAttributeOrderFixerTest.cpp",
    "QualifierFixerTest.cpp",
    "SortImportsTestJS.cpp",
    "SortImportsTestJava.cpp",
    "SortIncludesTest.cpp",
    "TokenAnnotatorTest.cpp",
    "UsingDeclarationsSorterTest.cpp",
  ]
}
