import("//build_overrides/llvm.gni")

llvm_executable("llvm-split") {
  deps = [
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRReader",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsAsmParsers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsCodeGens",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [ "llvm-split.cpp" ]
}
