import("//build_overrides/llvm.gni")

llvm_executable("clang-apply-replacements") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-apply-replacements",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}clang/lib/Tooling/Refactoring",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ "../include" ]
  sources = [ "ClangApplyReplacementsMain.cpp" ]
}
