import("//build_overrides/llvm.gni")

llvm_static_library("Expression") {
  output_name = "lldbExpression"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",

    #"${llvm_root_dir}lldb/source/Symbol", # FIXME: Dependency cycle.
    #"${llvm_root_dir}lldb/source/Target", # FIXME: Dependency cycle.
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",

    #"${llvm_root_dir}lldb/source/Plugins/Language/CPlusPlus", # 4-hop dependency cycle.

    # FIXME:
    # DEPENDS
    # intrinsics_gen
  ]
  include_dirs = [ ".." ]
  sources = [
    "DWARFExpression.cpp",
    "DWARFExpressionList.cpp",
    "DiagnosticManager.cpp",
    "Expression.cpp",
    "ExpressionParser.cpp",
    "ExpressionTypeSystemHelper.cpp",
    "ExpressionVariable.cpp",
    "FunctionCaller.cpp",
    "IRExecutionUnit.cpp",
    "IRInterpreter.cpp",
    "IRMemoryMap.cpp",
    "LLVMUserExpression.cpp",
    "Materializer.cpp",
    "ObjectFileJIT.cpp",
    "REPL.cpp",
    "UserExpression.cpp",
    "UtilityFunction.cpp",
  ]
}
