import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("MIRTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/CodeGen/MIRParser",
    "${llvm_root_dir}llvm/lib/FileCheck",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "MachineMetadata.cpp",
    "MachineStableHashTest.cpp",
  ]
}
