import("//build_overrides/llvm.gni")

llvm_static_library("ARCMigrate") {
  output_name = "clangARCMigrate"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Analysis",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Edit",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ARCMT.cpp",
    "ARCMTActions.cpp",
    "FileRemapper.cpp",
    "ObjCMT.cpp",
    "PlistReporter.cpp",
    "TransAPIUses.cpp",
    "TransARCAssign.cpp",
    "TransAutoreleasePool.cpp",
    "TransBlockObjCVariable.cpp",
    "TransEmptyStatementsAndDealloc.cpp",
    "TransGCAttrs.cpp",
    "TransGCCalls.cpp",
    "TransProperties.cpp",
    "TransProtectedScope.cpp",
    "TransRetainReleaseDealloc.cpp",
    "TransUnbridgedCasts.cpp",
    "TransUnusedInitDelegate.cpp",
    "TransZeroOutPropsInDealloc.cpp",
    "TransformActions.cpp",
    "Transforms.cpp",
  ]
}
