import("//build_overrides/llvm.gni")

llvm_static_library("ASTDiff") {
  output_name = "clangToolingASTDiff"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "ASTDiff.cpp" ]
}
