import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}third-party/unittest/unittest.gni")

tablegen("Opts") {
  visibility = [ ":OptionTests" ]
  args = [ "-gen-opt-parser-defs" ]
}

unittest("OptionTests") {
  deps = [
    ":Opts",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "OptionMarshallingTest.cpp",
    "OptionParsingTest.cpp",
  ]
}
