import("//build_overrides/llvm.gni")

llvm_static_library("Linux") {
  output_name = "lldbPluginPlatformLinux"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/Platform/POSIX",
    "${llvm_root_dir}lldb/source/Target",
  ]

  # Reaches into Plugins/Platform/POSIX.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "PlatformLinux.cpp" ]
}
