import("//build_overrides/llvm.gni")

llvm_static_library("Transformer") {
  output_name = "clangToolingTransformer"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}clang/lib/Tooling/Refactoring",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "Parsing.cpp",
    "RangeSelector.cpp",
    "RewriteRule.cpp",
    "SourceCode.cpp",
    "SourceCodeBuilders.cpp",
    "Stencil.cpp",
    "Transformer.cpp",
  ]
}
