import("//build_overrides/llvm.gni")

llvm_static_library("IRReader") {
  output_name = "LLVMIRReader"
  deps = [
    "${llvm_root_dir}llvm/lib/AsmParser",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "IRReader.cpp" ]
}
