import("//build_overrides/llvm.gni")

llvm_static_library("InstallAPI") {
  output_name = "clangInstallAPI"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TextAPI",
  ]
  sources = [
    "DiagnosticBuilderWrappers.cpp",
    "DirectoryScanner.cpp",
    "DylibVerifier.cpp",
    "FileList.cpp",
    "Frontend.cpp",
    "HeaderFile.cpp",
    "Library.cpp",
    "Visitor.cpp",
  ]
}
