import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}llvm/utils/gn/build/driver_executable.gni")

tablegen("InstallAPIOpts") {
  visibility = [ ":clang-installapi" ]
  args = [ "-gen-opt-parser-defs" ]
}

driver_executable("clang-installapi") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    ":InstallAPIOpts",
    "${llvm_root_dir}clang/lib/Driver",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/InstallAPI",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/TextAPI",
    "${llvm_root_dir}llvm/lib/TextAPI/BinaryReader",
  ]
  sources = [
    "ClangInstallAPI.cpp",
    "Options.cpp",
  ]
}
