import("//build_overrides/llvm.gni")

llvm_static_library("DataFormatters") {
  output_name = "lldbDataFormatters"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",

    #"${llvm_root_dir}lldb/source/Interpreter", # FIXME: Dependency cycle.
    #"${llvm_root_dir}lldb/source/Symbol", # FIXME: 3-hop Dependency cycle (DataFormatters->Symbol->Expression->Interpreter->DataFormatters)
    #"${llvm_root_dir}lldb/source/Target",  # FIXME: 3-hop Dependency cycle (DataFormatters->Target->Expression->Interpreter->DataFormatters)
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "CXXFunctionPointer.cpp",
    "DataVisualization.cpp",
    "DumpValueObjectOptions.cpp",
    "FormatCache.cpp",
    "FormatClasses.cpp",
    "FormatManager.cpp",
    "FormattersHelpers.cpp",
    "LanguageCategory.cpp",
    "StringPrinter.cpp",
    "TypeCategory.cpp",
    "TypeCategoryMap.cpp",
    "TypeFormat.cpp",
    "TypeSummary.cpp",
    "TypeSynthetic.cpp",
    "ValueObjectPrinter.cpp",
    "VectorType.cpp",
  ]
}
