import("//build_overrides/llvm.gni")

llvm_static_library("clang-doc") {
  output_name = "clangDoc"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Analysis",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Index",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "BitcodeReader.cpp",
    "BitcodeWriter.cpp",
    "ClangDoc.cpp",
    "Generators.cpp",
    "HTMLGenerator.cpp",
    "MDGenerator.cpp",
    "Mapper.cpp",
    "Representation.cpp",
    "Serialize.cpp",
    "YAMLGenerator.cpp",
  ]
}
