import("//build_overrides/llvm.gni")

llvm_static_library("DWARFLinker") {
  output_name = "LLVMDWARFLinkerBase"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "DWARFLinkerBase.cpp",
    "Utils.cpp",
  ]
}
