import("//build_overrides/llvm.gni")

llvm_static_library("InstCombine") {
  output_name = "LLVMInstCombine"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "InstCombineAddSub.cpp",
    "InstCombineAndOrXor.cpp",
    "InstCombineAtomicRMW.cpp",
    "InstCombineCalls.cpp",
    "InstCombineCasts.cpp",
    "InstCombineCompares.cpp",
    "InstCombineLoadStoreAlloca.cpp",
    "InstCombineMulDivRem.cpp",
    "InstCombineNegator.cpp",
    "InstCombinePHI.cpp",
    "InstCombineSelect.cpp",
    "InstCombineShifts.cpp",
    "InstCombineSimplifyDemanded.cpp",
    "InstCombineVectorOps.cpp",
    "InstructionCombining.cpp",
  ]
}
