import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("FrontendTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/CodeGen",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/FrontendTool",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ASTUnitTest.cpp",
    "CodeGenActionTest.cpp",
    "CompilerInstanceTest.cpp",
    "CompilerInvocationTest.cpp",
    "FixedPointString.cpp",
    "FrontendActionTest.cpp",
    "OutputStreamTest.cpp",
    "PCHPreambleTest.cpp",
    "ParsedSourceLocationTest.cpp",
    "ReparseWorkingDirTest.cpp",
    "TextDiagnosticTest.cpp",
    "UtilsTest.cpp",
  ]
}
