import("//build_overrides/llvm.gni")

llvm_static_library("Reader") {
  output_name = "LLVMBitReader"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/lib/Bitstream/Reader",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  sources = [
    "BitReader.cpp",
    "BitcodeAnalyzer.cpp",
    "BitcodeReader.cpp",
    "MetadataLoader.cpp",
    "ValueList.cpp",
  ]
}
