import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ASTMatchersTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Testing",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ASTMatchersInternalTest.cpp",
    "ASTMatchersNarrowingTest.cpp",
    "ASTMatchersNodeTest.cpp",
    "ASTMatchersTraversalTest.cpp",
    "GtestMatchersTest.cpp",
  ]
}
