import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("SandboxVectorizerTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/AsmParser",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/SandboxIR",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/Vectorize",
  ]
  sources = [
    "DependencyGraphTest.cpp",
    "IntervalTest.cpp",
    "LegalityTest.cpp",
  ]
}
