import("//build_overrides/llvm.gni")

llvm_static_library("bugprone") {
  output_name = "clangTidyBugproneModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/cppcoreguidelines",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Analysis",
    "${llvm_root_dir}clang/lib/Analysis/FlowSensitive",
    "${llvm_root_dir}clang/lib/Analysis/FlowSensitive/Models",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "ArgumentCommentCheck.cpp",
    "AssertSideEffectCheck.cpp",
    "AssignmentInIfConditionCheck.cpp",
    "BadSignalToKillThreadCheck.cpp",
    "BitwisePointerCastCheck.cpp",
    "BoolPointerImplicitConversionCheck.cpp",
    "BranchCloneCheck.cpp",
    "BugproneTidyModule.cpp",
    "CastingThroughVoidCheck.cpp",
    "ChainedComparisonCheck.cpp",
    "ComparePointerToMemberVirtualFunctionCheck.cpp",
    "CopyConstructorInitCheck.cpp",
    "CrtpConstructorAccessibilityCheck.cpp",
    "DanglingHandleCheck.cpp",
    "DynamicStaticInitializersCheck.cpp",
    "EasilySwappableParametersCheck.cpp",
    "EmptyCatchCheck.cpp",
    "ExceptionEscapeCheck.cpp",
    "FoldInitTypeCheck.cpp",
    "ForwardDeclarationNamespaceCheck.cpp",
    "ForwardingReferenceOverloadCheck.cpp",
    "ImplicitWideningOfMultiplicationResultCheck.cpp",
    "InaccurateEraseCheck.cpp",
    "IncDecInConditionsCheck.cpp",
    "IncorrectEnableIfCheck.cpp",
    "IncorrectRoundingsCheck.cpp",
    "InfiniteLoopCheck.cpp",
    "IntegerDivisionCheck.cpp",
    "LambdaFunctionNameCheck.cpp",
    "MacroParenthesesCheck.cpp",
    "MacroRepeatedSideEffectsCheck.cpp",
    "MisplacedOperatorInStrlenInAllocCheck.cpp",
    "MisplacedPointerArithmeticInAllocCheck.cpp",
    "MisplacedWideningCastCheck.cpp",
    "MoveForwardingReferenceCheck.cpp",
    "MultiLevelImplicitPointerConversionCheck.cpp",
    "MultipleNewInOneExpressionCheck.cpp",
    "MultipleStatementMacroCheck.cpp",
    "NoEscapeCheck.cpp",
    "NonZeroEnumToBoolConversionCheck.cpp",
    "NotNullTerminatedResultCheck.cpp",
    "OptionalValueConversionCheck.cpp",
    "ParentVirtualCallCheck.cpp",
    "PointerArithmeticOnPolymorphicObjectCheck.cpp",
    "PosixReturnCheck.cpp",
    "RedundantBranchConditionCheck.cpp",
    "ReservedIdentifierCheck.cpp",
    "ReturnConstRefFromParameterCheck.cpp",
    "SharedPtrArrayMismatchCheck.cpp",
    "SignalHandlerCheck.cpp",
    "SignedCharMisuseCheck.cpp",
    "SizeofContainerCheck.cpp",
    "SizeofExpressionCheck.cpp",
    "SmartPtrArrayMismatchCheck.cpp",
    "SpuriouslyWakeUpFunctionsCheck.cpp",
    "StandaloneEmptyCheck.cpp",
    "StringConstructorCheck.cpp",
    "StringIntegerAssignmentCheck.cpp",
    "StringLiteralWithEmbeddedNulCheck.cpp",
    "StringviewNullptrCheck.cpp",
    "SuspiciousEnumUsageCheck.cpp",
    "SuspiciousIncludeCheck.cpp",
    "SuspiciousMemoryComparisonCheck.cpp",
    "SuspiciousMemsetUsageCheck.cpp",
    "SuspiciousMissingCommaCheck.cpp",
    "SuspiciousReallocUsageCheck.cpp",
    "SuspiciousSemicolonCheck.cpp",
    "SuspiciousStringCompareCheck.cpp",
    "SuspiciousStringviewDataUsageCheck.cpp",
    "SwappedArgumentsCheck.cpp",
    "SwitchMissingDefaultCaseCheck.cpp",
    "TaggedUnionMemberCountCheck.cpp",
    "TerminatingContinueCheck.cpp",
    "ThrowKeywordMissingCheck.cpp",
    "TooSmallLoopVariableCheck.cpp",
    "UncheckedOptionalAccessCheck.cpp",
    "UndefinedMemoryManipulationCheck.cpp",
    "UndelegatedConstructorCheck.cpp",
    "UnhandledExceptionAtNewCheck.cpp",
    "UnhandledSelfAssignmentCheck.cpp",
    "UniquePtrArrayMismatchCheck.cpp",
    "UnsafeFunctionsCheck.cpp",
    "UnusedLocalNonTrivialVariableCheck.cpp",
    "UnusedRaiiCheck.cpp",
    "UnusedReturnValueCheck.cpp",
    "UseAfterMoveCheck.cpp",
    "VirtualNearMissCheck.cpp",
  ]
}
