import("//build_overrides/llvm.gni")

llvm_static_library("android") {
  output_name = "clangTidyAndroidModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AndroidTidyModule.cpp",
    "CloexecAccept4Check.cpp",
    "CloexecAcceptCheck.cpp",
    "CloexecCheck.cpp",
    "CloexecCreatCheck.cpp",
    "CloexecDupCheck.cpp",
    "CloexecEpollCreate1Check.cpp",
    "CloexecEpollCreateCheck.cpp",
    "CloexecFopenCheck.cpp",
    "CloexecInotifyInit1Check.cpp",
    "CloexecInotifyInitCheck.cpp",
    "CloexecMemfdCreateCheck.cpp",
    "CloexecOpenCheck.cpp",
    "CloexecPipe2Check.cpp",
    "CloexecPipeCheck.cpp",
    "CloexecSocketCheck.cpp",
    "ComparisonInTempFailureRetryCheck.cpp",
  ]
}
