import("//build_overrides/llvm.gni")

llvm_executable("llvm-mc") {
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "Disassembler.cpp",
    "llvm-mc.cpp",
  ]
}
