import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/lib/Target/targets.gni")

llvm_executable("llvm-mca") {
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/MCA",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsAsmParsers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDisassemblers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsMCAs",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  include_dirs = [
    ".",
    "include",
  ]
  sources = [
    "CodeRegion.cpp",
    "CodeRegionGenerator.cpp",
    "PipelinePrinter.cpp",
    "Views/BottleneckAnalysis.cpp",
    "Views/DispatchStatistics.cpp",
    "Views/InstructionInfoView.cpp",
    "Views/InstructionView.cpp",
    "Views/RegisterFileStatistics.cpp",
    "Views/ResourcePressureView.cpp",
    "Views/RetireControlUnitStatistics.cpp",
    "Views/SchedulerStatistics.cpp",
    "Views/SummaryView.cpp",
    "Views/TimelineView.cpp",
    "llvm-mca.cpp",
  ]
  defines = []
}
