import("//build_overrides/llvm.gni")

llvm_static_library("FuzzMutate") {
  output_name = "LLVMFuzzMutate"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
  ]
  sources = [
    "FuzzerCLI.cpp",
    "IRMutator.cpp",
    "OpDescriptor.cpp",
    "Operations.cpp",
    "RandomIRBuilder.cpp",
  ]
}
