import("//build_overrides/llvm.gni")

llvm_static_library("modernize") {
  output_name = "clangTidyModernizeModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/readability",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AvoidBindCheck.cpp",
    "AvoidCArraysCheck.cpp",
    "ConcatNestedNamespacesCheck.cpp",
    "DeprecatedHeadersCheck.cpp",
    "DeprecatedIosBaseAliasesCheck.cpp",
    "IntegralLiteralExpressionMatcher.cpp",
    "LoopConvertCheck.cpp",
    "LoopConvertUtils.cpp",
    "MacroToEnumCheck.cpp",
    "MakeSharedCheck.cpp",
    "MakeSmartPtrCheck.cpp",
    "MakeUniqueCheck.cpp",
    "MinMaxUseInitializerListCheck.cpp",
    "ModernizeTidyModule.cpp",
    "PassByValueCheck.cpp",
    "RawStringLiteralCheck.cpp",
    "RedundantVoidArgCheck.cpp",
    "ReplaceAutoPtrCheck.cpp",
    "ReplaceDisallowCopyAndAssignMacroCheck.cpp",
    "ReplaceRandomShuffleCheck.cpp",
    "ReturnBracedInitListCheck.cpp",
    "ShrinkToFitCheck.cpp",
    "TypeTraitsCheck.cpp",
    "UnaryStaticAssertCheck.cpp",
    "UseAutoCheck.cpp",
    "UseBoolLiteralsCheck.cpp",
    "UseConstraintsCheck.cpp",
    "UseDefaultMemberInitCheck.cpp",
    "UseDesignatedInitializersCheck.cpp",
    "UseEmplaceCheck.cpp",
    "UseEqualsDefaultCheck.cpp",
    "UseEqualsDeleteCheck.cpp",
    "UseNodiscardCheck.cpp",
    "UseNoexceptCheck.cpp",
    "UseNullptrCheck.cpp",
    "UseOverrideCheck.cpp",
    "UseRangesCheck.cpp",
    "UseStartsEndsWithCheck.cpp",
    "UseStdFormatCheck.cpp",
    "UseStdNumbersCheck.cpp",
    "UseStdPrintCheck.cpp",
    "UseTrailingReturnTypeCheck.cpp",
    "UseTransparentFunctorsCheck.cpp",
    "UseUncaughtExceptionsCheck.cpp",
    "UseUsingCheck.cpp",
  ]
}
