import("//build_overrides/llvm.gni")

llvm_static_library("TargetParser") {
  output_name = "LLVMTargetParser"
  deps = [ "${llvm_root_dir}llvm/lib/Support" ]
  public_deps = [ "${llvm_root_dir}llvm/include/llvm/TargetParser:gen" ]
  include_dirs = [
    "Unix",
    "Windows",
  ]
  sources = [
    "AArch64TargetParser.cpp",
    "ARMTargetParser.cpp",
    "ARMTargetParserCommon.cpp",
    "CSKYTargetParser.cpp",
    "Host.cpp",
    "LoongArchTargetParser.cpp",
    "PPCTargetParser.cpp",
    "RISCVISAInfo.cpp",
    "RISCVTargetParser.cpp",
    "SubtargetFeature.cpp",
    "TargetParser.cpp",
    "Triple.cpp",
    "X86TargetParser.cpp",
  ]
}
