import("//build_overrides/llvm.gni")

llvm_executable("llvm-dwarfdump") {
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "SectionSizes.cpp",
    "Statistics.cpp",
    "llvm-dwarfdump.cpp",
  ]
}
