import("//build_overrides/llvm.gni")

llvm_static_library("RuntimeDyld") {
  output_name = "LLVMRuntimeDyld"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "JITSymbol.cpp",
    "RTDyldMemoryManager.cpp",
    "RuntimeDyld.cpp",
    "RuntimeDyldCOFF.cpp",
    "RuntimeDyldChecker.cpp",
    "RuntimeDyldELF.cpp",
    "RuntimeDyldMachO.cpp",
    "Targets/RuntimeDyldELFMips.cpp",
  ]
}
