import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("SymbolFileDWARFProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("SymbolFileDWARFPropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "SymbolFileDWARFProperties.td"
}

llvm_static_library("DWARF") {
  output_name = "lldbPluginSymbolFileDWARF"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    ":SymbolFileDWARFProperties",
    ":SymbolFileDWARFPropertiesEnum",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/ExpressionParser/Clang",

    #"${llvm_root_dir}lldb/source/Plugins/Language/CPlusPlus", # 3-hop dependency cycle.
    "${llvm_root_dir}lldb/source/Plugins/Language/ObjC",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",

    #"${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang", # Dependency cycle.
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Uses source-relative includes for own headers.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "AppleDWARFIndex.cpp",
    "DIERef.cpp",
    "DWARFASTParser.cpp",
    "DWARFASTParserClang.cpp",
    "DWARFAttribute.cpp",
    "DWARFBaseDIE.cpp",
    "DWARFCompileUnit.cpp",
    "DWARFContext.cpp",
    "DWARFDIE.cpp",
    "DWARFDataExtractor.cpp",
    "DWARFDebugAranges.cpp",
    "DWARFDebugInfo.cpp",
    "DWARFDebugInfoEntry.cpp",
    "DWARFDebugMacro.cpp",
    "DWARFDebugRanges.cpp",
    "DWARFDeclContext.cpp",
    "DWARFDefines.cpp",
    "DWARFFormValue.cpp",
    "DWARFIndex.cpp",
    "DWARFTypeUnit.cpp",
    "DWARFUnit.cpp",
    "DebugNamesDWARFIndex.cpp",
    "LogChannelDWARF.cpp",
    "ManualDWARFIndex.cpp",
    "NameToDIE.cpp",
    "SymbolFileDWARF.cpp",
    "SymbolFileDWARFDebugMap.cpp",
    "SymbolFileDWARFDwo.cpp",
    "UniqueDWARFASTType.cpp",
  ]
}
