import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("DebugInfoCodeViewTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "GUIDFormatTest.cpp",
    "RandomAccessVisitorTest.cpp",
    "TypeHashingTest.cpp",
    "TypeIndexDiscoveryTest.cpp",
  ]
}
