import("//build_overrides/llvm.gni")

llvm_static_library("Classic") {
  output_name = "LLVMDWARFLinker"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/DWARFLinker",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DWARFLinker.cpp",
    "DWARFLinkerCompileUnit.cpp",
    "DWARFLinkerDeclContext.cpp",
    "DWARFStreamer.cpp",
  ]
}
