import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")

tablegen("Options") {
  visibility = [ ":llvm-dwarfutil" ]
  args = [ "-gen-opt-parser-defs" ]
}

llvm_executable("llvm-dwarfutil") {
  deps = [
    ":Options",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/DWARFLinker",
    "${llvm_root_dir}llvm/lib/DWARFLinker/Classic",
    "${llvm_root_dir}llvm/lib/DWARFLinker/Parallel",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/ObjCopy",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsCodeGens",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DebugInfoLinker.cpp",
    "llvm-dwarfutil.cpp",
  ]
}
