import("//build_overrides/llvm.gni")

llvm_static_library("Profile") {
  output_name = "LLVMBOLTProfile"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:bolt_code" ]
  deps = [
    "${llvm_root_dir}bolt/lib/Core",
    "${llvm_root_dir}bolt/lib/Passes",
    "${llvm_root_dir}bolt/lib/Utils",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "BoltAddressTranslation.cpp",
    "DataAggregator.cpp",
    "DataReader.cpp",
    "Heatmap.cpp",
    "StaleProfileMatching.cpp",
    "YAMLProfileReader.cpp",
    "YAMLProfileWriter.cpp",
  ]
}
