import("//build_overrides/llvm.gni")

llvm_static_library("Object") {
  output_name = "LLVMObject"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/include/llvm/Support:write_vcsrevision",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRReader",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/TextAPI",
  ]

  sources = [
    "Archive.cpp",
    "ArchiveWriter.cpp",
    "Binary.cpp",
    "BuildID.cpp",
    "COFFImportFile.cpp",
    "COFFModuleDefinition.cpp",
    "COFFObjectFile.cpp",
    "DXContainer.cpp",
    "Decompressor.cpp",
    "ELF.cpp",
    "ELFObjectFile.cpp",
    "Error.cpp",
    "FaultMapParser.cpp",
    "GOFFObjectFile.cpp",
    "IRObjectFile.cpp",
    "IRSymtab.cpp",
    "MachOObjectFile.cpp",
    "MachOUniversal.cpp",
    "MachOUniversalWriter.cpp",
    "Minidump.cpp",
    "ModuleSymbolTable.cpp",
    "Object.cpp",
    "ObjectFile.cpp",
    "OffloadBinary.cpp",
    "RecordStreamer.cpp",
    "RelocationResolver.cpp",
    "SymbolSize.cpp",
    "SymbolicFile.cpp",
    "TapiFile.cpp",
    "TapiUniversal.cpp",
    "WasmObjectFile.cpp",
    "WindowsMachineFlag.cpp",
    "WindowsResource.cpp",
    "XCOFFObjectFile.cpp",
  ]
}
