import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}llvm/utils/gn/build/driver_executable.gni")

tablegen("Opts") {
  visibility = [ ":llvm-ifs" ]
  args = [ "-gen-opt-parser-defs" ]
}

driver_executable("llvm-ifs") {
  deps = [
    ":Opts",
    "${llvm_root_dir}llvm/lib/InterfaceStub",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/TextAPI",
  ]
  sources = [
    "ErrorCollector.cpp",
    "llvm-ifs.cpp",
  ]
}
