import("//build_overrides/llvm.gni")

# source_set instead of static_library so that all test cpp files are loaded.
llvm_source_set("X86") {
  testonly = true
  deps = [
    "${llvm_root_dir}llvm/lib/Target/X86",
    "${llvm_root_dir}third-party/unittest:gtest",

    # This test target reaches inside the Target/X86 tablegen internals and must
    # depend on this Target/X86-internal build target.
    "${llvm_root_dir}llvm/lib/Target/X86/MCTargetDesc",
  ]
  include_dirs = [
    "..",
    "${llvm_root_dir}llvm/lib/Target/X86",
    "${llvm_root_dir}llvm/tools/llvm-mca",
  ]
  sources = [
    "TestIncrementalMCA.cpp",
    "X86TestBase.cpp",
  ]
}
