import("//build_overrides/llvm.gni")

llvm_static_library("Clang") {
  output_name = "lldbPluginExpressionParserClang"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/CodeGen",
    "${llvm_root_dir}clang/lib/Driver",
    "${llvm_root_dir}clang/lib/Edit",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Frontend/Rewrite",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Parse",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",

    #"${llvm_root_dir}lldb/source/Plugins/Language/CPlusPlus", # 3-hop dependency cycle
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/CPlusPlus",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/ObjC",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/MCJIT",

    #"${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang", # Dependency cycle
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
  ]

  # Uses source-relative paths for own includes (!)
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "ASTResultSynthesizer.cpp",
    "ASTStructExtractor.cpp",
    "ASTUtils.cpp",
    "ClangASTImporter.cpp",
    "ClangASTMetadata.cpp",
    "ClangASTSource.cpp",
    "ClangDeclVendor.cpp",
    "ClangExpressionDeclMap.cpp",
    "ClangExpressionHelper.cpp",
    "ClangExpressionParser.cpp",
    "ClangExpressionSourceCode.cpp",
    "ClangExpressionUtil.cpp",
    "ClangExpressionVariable.cpp",
    "ClangExternalASTSourceCallbacks.cpp",
    "ClangFunctionCaller.cpp",
    "ClangHost.cpp",
    "ClangModulesDeclVendor.cpp",
    "ClangPersistentVariables.cpp",
    "ClangUserExpression.cpp",
    "ClangUtil.cpp",
    "ClangUtilityFunction.cpp",
    "CppModuleConfiguration.cpp",
    "CxxModuleHandler.cpp",
    "IRDynamicChecks.cpp",
    "IRForTarget.cpp",
    "NameSearchContext.cpp",
  ]
}
