declare_args() {
  # Build for debugging. Equivalent to is_optimized=false symbol_level=2.
  is_debug = false

  # Path of sysroot to use.
  sysroot = ""

  # glibc is at least 2.33 which has mallinfo2.
  # TODO: remove this once nobody using the gn build is building against an old glibc.
  llvm_have_mallinfo2 = current_os == "linux"

# Set this to a clang build directory. If set, that clang is used as compiler.
  # On Windows, setting this also causes lld-link to be used as linker.
  # Example value: getenv("HOME") + "/src/llvm-build/Release+Asserts"
  clang_base_path = ""
}

declare_args() {
  if (is_debug) {
    # Debug info symbol level. 0: No symbols; 1: Line numbers; 2: Full symbols.
    symbol_level = 2
  } else {
    # Debug info symbol level. 0: No symbols; 1: Line numbers; 2: Full symbols.
    symbol_level = 0
  }

# Set if the host compiler is clang.  On by default on Mac or if
  # clang_base_path is set.
  is_clang = host_os == "mac" || clang_base_path != ""

  # Set this to true to link with LLD instead of the default linker.
  use_lld = clang_base_path != ""
}

llvm_root_dir = "//"
llvm_root_gen_dir = "${root_gen_dir}"

# All targets will get this list of configs by default.
# Targets can opt out of a config by removing it from their local configs list.
# If you're adding global flags and don't need targets to be able to opt out,
# add the flags to compiler_defaults, not to a new config.
shared_binary_target_configs = [
  "${llvm_root_dir}llvm/utils/gn/build:compiler_defaults",
  "${llvm_root_dir}llvm/utils/gn/build:llvm_code",
  "${llvm_root_dir}llvm/utils/gn/build:no_exceptions",
  "${llvm_root_dir}llvm/utils/gn/build:no_rtti",
  "${llvm_root_dir}llvm/utils/gn/build:thin_archive",
  "${llvm_root_dir}llvm/utils/gn/build:warn_covered_switch_default",
]

llvm_compiled_action_bin_dir = "bin/"

template("llvm_executable") {
  executable(target_name) {
    forward_variables_from(invoker, "*")
  }
}

template("llvm_loadable_module") {
  loadable_module(target_name) {
    forward_variables_from(invoker, "*")
  }
}

template("llvm_static_library") {
  static_library(target_name) {
    forward_variables_from(invoker, "*")
  }
}

template("llvm_shared_library") {
  shared_library(target_name) {
    forward_variables_from(invoker, "*")
  }
}

template("llvm_source_set") {
  source_set(target_name) {
    forward_variables_from(invoker, "*")
  }
}

set_defaults("llvm_executable") {
  configs = shared_binary_target_configs
}
set_defaults("llvm_loadable_module") {
  configs = shared_binary_target_configs
}
set_defaults("llvm_static_library") {
  configs = shared_binary_target_configs
}
set_defaults("llvm_shared_library") {
  configs = shared_binary_target_configs + [ "${llvm_root_dir}llvm/utils/gn/build:zdefs" ]
}
set_defaults("llvm_source_set") {
  configs = shared_binary_target_configs
}
