import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("CoreProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("CorePropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "CoreProperties.td"
}

llvm_static_library("Core") {
  output_name = "lldbCore"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    ":CoreProperties",
    ":CorePropertiesEnum",
    "${llvm_root_dir}clang/lib/Driver",

    #"${llvm_root_dir}lldb/source/Breakpoint", # Dependency cycle.
    #"${llvm_root_dir}lldb/source/DataFormatters", # Dependency cycle.
    #"${llvm_root_dir}lldb/source/Expression", # Dependency cycle.
    "${llvm_root_dir}lldb/source/Host",

    #"${llvm_root_dir}lldb/source/Interpreter", # Dependency cycle.
    #"${llvm_root_dir}lldb/source/Symbol", # Dependency cycle.
    #"${llvm_root_dir}lldb/source/Target", # Dependency cycle.
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",

    #"${llvm_root_dir}lldb/source/Plugins/Language/CPlusPlus", # 3-hop dependency cycle.
    #"${llvm_root_dir}lldb/source/Plugins/Language/ObjC",  # Many-hop dependency cycle.

    # FIXME:
    #  ${LLDB_CURSES_LIBS}
  ]

  # FIXME: Link curses, libedit if needed.
  include_dirs = [ ".." ]
  sources = [
    "Address.cpp",
    "AddressRange.cpp",
    "AddressRangeListImpl.cpp",
    "AddressResolver.cpp",
    "AddressResolverFileLine.cpp",
    "Communication.cpp",
    "DataFileCache.cpp",
    "Debugger.cpp",
    "DebuggerEvents.cpp",
    "Declaration.cpp",
    "Disassembler.cpp",
    "DumpDataExtractor.cpp",
    "DumpRegisterInfo.cpp",
    "DumpRegisterValue.cpp",
    "DynamicLoader.cpp",
    "EmulateInstruction.cpp",
    "FileLineResolver.cpp",
    "FormatEntity.cpp",
    "Highlighter.cpp",
    "IOHandler.cpp",
    "IOHandlerCursesGUI.cpp",
    "Mangled.cpp",
    "Module.cpp",
    "ModuleChild.cpp",
    "ModuleList.cpp",
    "Opcode.cpp",
    "PluginManager.cpp",
    "Progress.cpp",
    "RichManglingContext.cpp",
    "SearchFilter.cpp",
    "Section.cpp",
    "SourceLocationSpec.cpp",
    "SourceManager.cpp",
    "StreamAsynchronousIO.cpp",
    "ThreadedCommunication.cpp",
    "UserSettingsController.cpp",
    "Value.cpp",
    "ValueObject.cpp",
    "ValueObjectCast.cpp",
    "ValueObjectChild.cpp",
    "ValueObjectConstResult.cpp",
    "ValueObjectConstResultCast.cpp",
    "ValueObjectConstResultChild.cpp",
    "ValueObjectConstResultImpl.cpp",
    "ValueObjectDynamicValue.cpp",
    "ValueObjectList.cpp",
    "ValueObjectMemory.cpp",
    "ValueObjectRegister.cpp",
    "ValueObjectSyntheticFilter.cpp",
    "ValueObjectUpdater.cpp",
    "ValueObjectVTable.cpp",
    "ValueObjectVariable.cpp",
  ]
}
