import("//build_overrides/llvm.gni")

llvm_static_library("clang-include-fixer") {
  output_name = "clangIncludeFixer"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-include-fixer/find-all-symbols",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Parse",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "FuzzySymbolIndex.cpp",
    "InMemorySymbolIndex.cpp",
    "IncludeFixer.cpp",
    "IncludeFixerContext.cpp",
    "SymbolIndexManager.cpp",
    "YamlSymbolIndex.cpp",
  ]
}
