import("//build_overrides/llvm.gni")

llvm_static_library("LTO") {
  output_name = "LLVMLTO"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/Extensions",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Linker",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/AggressiveInstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
    "${llvm_root_dir}llvm/lib/Transforms/InstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/ObjCARC",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "LTO.cpp",
    "LTOBackend.cpp",
    "LTOCodeGenerator.cpp",
    "LTOModule.cpp",
    "ThinLTOCodeGenerator.cpp",
    "UpdateCompilerUsed.cpp",
  ]
}
