import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("BinaryFormatTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DwarfTest.cpp",
    "ELFTest.cpp",
    "MachOTest.cpp",
    "MsgPackDocumentTest.cpp",
    "MsgPackReaderTest.cpp",
    "MsgPackWriterTest.cpp",
    "TestFileMagic.cpp",
  ]
}
