import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("TargetParserTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "CSKYTargetParserTest.cpp",
    "Host.cpp",
    "RISCVISAInfoTest.cpp",
    "RISCVTargetParserTest.cpp",
    "TargetParserTest.cpp",
    "TripleTest.cpp",
  ]
}
