import("//build_overrides/llvm.gni")

llvm_static_library("minidump") {
  output_name = "lldbPluginProcessMinidump"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Plugins/Process/elf-core",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "MinidumpParser.cpp",
    "MinidumpTypes.cpp",
    "ProcessMinidump.cpp",
    "RegisterContextMinidump_ARM.cpp",
    "RegisterContextMinidump_ARM64.cpp",
    "RegisterContextMinidump_x86_32.cpp",
    "RegisterContextMinidump_x86_64.cpp",
    "ThreadMinidump.cpp",
  ]
}
