import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}llvm/utils/gn/build/driver_executable.gni")

tablegen("Opts") {
  visibility = [ ":llvm-cgdata" ]
  args = [ "-gen-opt-parser-defs" ]
}

driver_executable("llvm-cgdata") {
  deps = [
    ":Opts",
    "${llvm_root_dir}llvm/lib/CGData",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "llvm-cgdata.cpp" ]
}
