import("//build_overrides/llvm.gni")

llvm_static_library("POSIX") {
  output_name = "lldbPluginPlatformPOSIX"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/Platform/gdb-server",
    "${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang",
    "${llvm_root_dir}lldb/source/Target",
  ]

  # Reaches into Plugins/TypeSystem/Clang.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "PlatformPOSIX.cpp" ]
}
