import("//build_overrides/llvm.gni")

llvm_executable("llvm-xray") {
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/XRay",
  ]
  sources = [
    "func-id-helper.cpp",
    "llvm-xray.cpp",
    "xray-account.cpp",
    "xray-color-helper.cpp",
    "xray-converter.cpp",
    "xray-extract.cpp",
    "xray-fdr-dump.cpp",
    "xray-graph-diff.cpp",
    "xray-graph.cpp",
    "xray-registry.cpp",
    "xray-stacks.cpp",
  ]
}
