import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/gn/build/compiled_action.gni")

compiled_action("Confusables.inc") {
  tool = "ConfusableTable:clang-tidy-confusable-chars-gen"
  inputs = [ "ConfusableTable/confusables.txt" ]
  outputs = [ "$target_gen_dir/$target_name" ]
  args = [
    rebase_path(inputs[0], root_build_dir),
    rebase_path(outputs[0], root_build_dir),
  ]
}

llvm_static_library("misc") {
  output_name = "clangTidyMiscModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  include_dirs = [
    target_gen_dir,
    "${llvm_root_dir}clang-tools-extra/include-cleaner/include",
  ]
  deps = [
    ":Confusables.inc",
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang-tools-extra/include-cleaner/lib",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Analysis",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "ConfusableIdentifierCheck.cpp",
    "ConstCorrectnessCheck.cpp",
    "CoroutineHostileRAIICheck.cpp",
    "DefinitionsInHeadersCheck.cpp",
    "HeaderIncludeCycleCheck.cpp",
    "IncludeCleanerCheck.cpp",
    "MiscTidyModule.cpp",
    "MisleadingBidirectional.cpp",
    "MisleadingIdentifier.cpp",
    "MisplacedConstCheck.cpp",
    "NewDeleteOverloadsCheck.cpp",
    "NoRecursionCheck.cpp",
    "NonCopyableObjects.cpp",
    "NonPrivateMemberVariablesInClassesCheck.cpp",
    "RedundantExpressionCheck.cpp",
    "StaticAssertCheck.cpp",
    "ThrowByValueCatchByReferenceCheck.cpp",
    "UnconventionalAssignOperatorCheck.cpp",
    "UniqueptrResetReleaseCheck.cpp",
    "UnusedAliasDeclsCheck.cpp",
    "UnusedParametersCheck.cpp",
    "UnusedUsingDeclsCheck.cpp",
    "UseAnonymousNamespaceCheck.cpp",
    "UseInternalLinkageCheck.cpp",
  ]
}
