import("//build_overrides/llvm.gni")

llvm_static_library("SandboxIR") {
  output_name = "LLVMSandboxIR"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "Argument.cpp",
    "BasicBlock.cpp",
    "Constant.cpp",
    "Context.cpp",
    "Function.cpp",
    "Instruction.cpp",
    "Module.cpp",
    "Pass.cpp",
    "PassManager.cpp",
    "Region.cpp",
    "Tracker.cpp",
    "Type.cpp",
    "Use.cpp",
    "User.cpp",
    "Value.cpp",
  ]
}
