import("//build_overrides/llvm.gni")

group("lib") {
  deps = [
    "${llvm_root_dir}compiler-rt/lib/asan:ignorelist($host_toolchain)",
    "${llvm_root_dir}compiler-rt/lib/builtins",
    "${llvm_root_dir}compiler-rt/lib/cfi:ignorelist($host_toolchain)",
  ]
  if (current_os == "linux" && current_cpu == "x64") {
    deps += [ "${llvm_root_dir}compiler-rt/lib/msan" ]
  }
  if (current_os == "linux" || current_os == "android") {
    deps += [ "${llvm_root_dir}compiler-rt/lib/ubsan_minimal" ]
  }
  if (current_os != "baremetal") {
    deps += [
      "${llvm_root_dir}compiler-rt/lib/asan",
      "${llvm_root_dir}compiler-rt/lib/profile",
    ]
  }
  if (current_os != "win" && current_os != "baremetal") {
    deps += [ "${llvm_root_dir}compiler-rt/lib/ubsan" ]
    if (current_cpu == "x64" || current_cpu == "arm64") {
      deps += [ "${llvm_root_dir}compiler-rt/lib/tsan/rtl" ]
    }
  }
}
