import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("FuzzMutateTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/AsmParser",
    "${llvm_root_dir}llvm/lib/FuzzMutate",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "OperationsTest.cpp",
    "RandomIRBuilderTest.cpp",
    "ReservoirSamplerTest.cpp",
    "StrategiesTest.cpp",
  ]
}
