import("//build_overrides/llvm.gni")

llvm_static_library("LLVMC") {
  output_name = "lldbPluginDisassemblerLLVMC"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/RuntimeDyld",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCDisassembler",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [ "DisassemblerLLVMC.cpp" ]
}
