import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}third-party/unittest/unittest.gni")

tablegen("AutomataAutomata") {
  visibility = [ ":TableGenTests" ]
  args = [ "-gen-automata" ]
  td_file = "Automata.td"
}

tablegen("AutomataTables") {
  visibility = [ ":TableGenTests" ]
  args = [ "-gen-searchable-tables" ]
  td_file = "Automata.td"
}

unittest("TableGenTests") {
  deps = [
    ":AutomataAutomata",
    ":AutomataTables",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TableGen",
    "${llvm_root_dir}llvm/utils/TableGen/Common",
  ]
  include_dirs = [ "${llvm_root_dir}llvm/utils/TableGen" ]
  sources = [
    "AutomataTest.cpp",
    "CodeExpanderTest.cpp",
    "ParserEntryPointTest.cpp",
  ]
}
