import("//build_overrides/llvm.gni")

llvm_static_library("BinaryReader") {
  output_name = "LLVMTextAPIBinaryReader"
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/TextAPI",
  ]
  sources = [ "DylibReader.cpp" ]
}
