import("//build_overrides/llvm.gni")

llvm_static_library("Testing") {
  output_name = "clangTesting"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  testonly = true
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}third-party/unittest:gtest",
  ]
  sources = [
    "CommandLineArgs.cpp",
    "TestAST.cpp",
  ]
}
