import("//build_overrides/llvm.gni")

llvm_executable("llc") {
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/CodeGen/MIRParser",
    "${llvm_root_dir}llvm/lib/CodeGen/SelectionDAG",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRPrinter",
    "${llvm_root_dir}llvm/lib/IRReader",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/lib/Transforms/Vectorize",
  ]
  sources = [
    "NewPMDriver.cpp",
    "llc.cpp",
  ]

  # Support plugins.
  # FIXME: Disable dead stripping once other binaries are dead-stripped.
  if (host_os != "mac" && host_os != "win") {
    # Corresponds to export_executable_symbols() in cmake.
    ldflags = [ "-rdynamic" ]
  }
}
