import("//build_overrides/llvm.gni")

llvm_executable("llvm-profgen") {
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCDisassembler",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ProfileData",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDisassemblers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
  ]
  sources = [
    "CSPreInliner.cpp",
    "MissingFrameInferrer.cpp",
    "PerfReader.cpp",
    "ProfileGenerator.cpp",
    "ProfiledBinary.cpp",
    "llvm-profgen.cpp",
  ]
}
