import("//build_overrides/llvm.gni")

llvm_static_library("Analysis") {
  output_name = "clangAnalysis"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/include/clang/AST:StmtDataCollectors",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AnalysisDeclContext.cpp",
    "BodyFarm.cpp",
    "CFG.cpp",
    "CFGReachabilityAnalysis.cpp",
    "CFGStmtMap.cpp",
    "CallGraph.cpp",
    "CalledOnceCheck.cpp",
    "CloneDetection.cpp",
    "CocoaConventions.cpp",
    "CodeInjector.cpp",
    "ConstructionContext.cpp",
    "Consumed.cpp",
    "Dominators.cpp",
    "ExprMutationAnalyzer.cpp",
    "IntervalPartition.cpp",
    "IssueHash.cpp",
    "LiveVariables.cpp",
    "MacroExpansionContext.cpp",
    "ObjCNoReturn.cpp",
    "PathDiagnostic.cpp",
    "PostOrderCFGView.cpp",
    "ProgramPoint.cpp",
    "ReachableCode.cpp",
    "RetainSummaryManager.cpp",
    "ThreadSafety.cpp",
    "ThreadSafetyCommon.cpp",
    "ThreadSafetyLogical.cpp",
    "ThreadSafetyTIL.cpp",
    "UninitializedValues.cpp",
    "UnsafeBufferUsage.cpp",
  ]
}
