import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("LLVMFrontendTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/Frontend/OpenACC",
    "${llvm_root_dir}llvm/lib/Frontend/OpenMP",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "OpenACCTest.cpp",
    "OpenMPCompositionTest.cpp",
    "OpenMPContextTest.cpp",
    "OpenMPDecompositionTest.cpp",
    "OpenMPIRBuilderTest.cpp",
    "OpenMPParsingTest.cpp",
  ]
}
