import("//build_overrides/llvm.gni")

llvm_static_library("Interpreter") {
  output_name = "LLVMInterpreter"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "Execution.cpp",
    "ExternalFunctions.cpp",
    "Interpreter.cpp",
  ]
}
