import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("SystemZAsmLexerTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target/SystemZ",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [ "SystemZAsmLexerTest.cpp" ]
}
