import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/gn/build/fuzzer.gni")

fuzzer("llvm-opt-fuzzer") {
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/FuzzMutate",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRReader",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/AggressiveInstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/Coroutines",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
    "${llvm_root_dir}llvm/lib/Transforms/InstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/Instrumentation",
    "${llvm_root_dir}llvm/lib/Transforms/ObjCARC",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/lib/Transforms/Vectorize",
  ]
  dummy_main = "DummyOptFuzzer.cpp"
  sources = [ "llvm-opt-fuzzer.cpp" ]
}
