import("//build_overrides/llvm.gni")

llvm_static_library("conversions") {
  output_name = "clangdXpcJsonConversions"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clangd",
    "${llvm_root_dir}clang-tools-extra/clangd/support",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ ".." ]
  sources = [ "Conversion.cpp" ]
}

llvm_static_library("transport") {
  output_name = "clangdXpcTransport"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    ":conversions",
    "${llvm_root_dir}clang-tools-extra/clangd",
    "${llvm_root_dir}clang-tools-extra/clangd:features",
    "${llvm_root_dir}clang-tools-extra/clangd/support",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ ".." ]
  sources = [ "XPCTransport.cpp" ]
}
