import("//build_overrides/llvm.gni")

llvm_static_library("Clang") {
  output_name = "lldbPluginClangREPL"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/DataFormatters",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/Language/ClangCommon",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/CPlusPlus",
    "${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "ClangREPL.cpp" ]
}
