import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}llvm/utils/gn/build/driver_executable.gni")

tablegen("Opts") {
  visibility = [ ":llvm-ml" ]
  args = [ "-gen-opt-parser-defs" ]
}

driver_executable("llvm-ml") {
  deps = [
    ":Opts",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "Disassembler.cpp",
    "llvm-ml.cpp",
  ]
}
