import("//build_overrides/llvm.gni")

llvm_executable("clangd-xpc-test-client") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clangd",
    "${llvm_root_dir}clang-tools-extra/clangd/xpc:conversions",
    "${llvm_root_dir}clang-tools-extra/clangd/xpc/framework:ClangdXPC.framework",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  include_dirs = [ "../.." ]
  sources = [ "ClangdXPCTestClient.cpp" ]
}
