import("//build_overrides/llvm.gni")

llvm_executable("dexp") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clangd",
    "${llvm_root_dir}clang-tools-extra/clangd:features",
    "${llvm_root_dir}clang-tools-extra/clangd/index/remote/unimplemented",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}llvm/lib/LineEditor",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ "../../.." ]
  sources = [ "Dexp.cpp" ]
}
