import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("DynamicLoaderDarwinProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("DynamicLoaderDarwinPropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "DynamicLoaderDarwinProperties.td"
}

llvm_static_library("MacOSX-DYLD") {
  output_name = "lldbPluginDynamicLoaderMacOSXDYLD"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    ":DynamicLoaderDarwinProperties",
    ":DynamicLoaderDarwinPropertiesEnum",
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  # Reaches into Plugins/LanguageRuntime/ObjC.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "DynamicLoaderDarwin.cpp",
    "DynamicLoaderDarwinProperties.cpp",
    "DynamicLoaderMacOS.cpp",
    "DynamicLoaderMacOSXDYLD.cpp",
  ]
}
