import("//build_overrides/llvm.gni")

llvm_static_library("Coroutines") {
  output_name = "LLVMCoroutines"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "CoroAnnotationElide.cpp",
    "CoroCleanup.cpp",
    "CoroConditionalWrapper.cpp",
    "CoroEarly.cpp",
    "CoroElide.cpp",
    "CoroFrame.cpp",
    "CoroSplit.cpp",
    "Coroutines.cpp",
    "MaterializationUtils.cpp",
    "SpillUtils.cpp",
    "SuspendCrossingInfo.cpp",
  ]
}
