import("//build_overrides/llvm.gni")

llvm_static_library("ObjCARC") {
  output_name = "LLVMObjCARCOpts"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "DependencyAnalysis.cpp",
    "ObjCARC.cpp",
    "ObjCARCAPElim.cpp",
    "ObjCARCContract.cpp",
    "ObjCARCExpand.cpp",
    "ObjCARCOpts.cpp",
    "ProvenanceAnalysis.cpp",
    "ProvenanceAnalysisEvaluator.cpp",
    "PtrState.cpp",
  ]
}
