import("//build_overrides/llvm.gni")

llvm_static_library("Parse") {
  output_name = "clangParse"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/include/clang/Parse:AttrParserStringSwitches",
    "${llvm_root_dir}clang/include/clang/Parse:AttrSubMatchRulesParserStringSwitches",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}llvm/lib/Frontend/OpenMP",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ParseAST.cpp",
    "ParseCXXInlineMethods.cpp",
    "ParseDecl.cpp",
    "ParseDeclCXX.cpp",
    "ParseExpr.cpp",
    "ParseExprCXX.cpp",
    "ParseHLSL.cpp",
    "ParseInit.cpp",
    "ParseObjc.cpp",
    "ParseOpenACC.cpp",
    "ParseOpenMP.cpp",
    "ParsePragma.cpp",
    "ParseStmt.cpp",
    "ParseStmtAsm.cpp",
    "ParseTemplate.cpp",
    "ParseTentative.cpp",
    "Parser.cpp",
  ]
}
