import("//build_overrides/llvm.gni")

llvm_static_library("Index") {
  output_name = "clangIndex"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "CommentToXML.cpp",
    "FileIndexRecord.cpp",
    "IndexBody.cpp",
    "IndexDecl.cpp",
    "IndexSymbol.cpp",
    "IndexTypeSourceInfo.cpp",
    "IndexingAction.cpp",
    "IndexingContext.cpp",
    "IndexingContext.h",
    "USRGeneration.cpp",
  ]
}
