import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ClangAnalysisFlowSensitiveTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Analysis",
    "${llvm_root_dir}clang/lib/Analysis/FlowSensitive",
    "${llvm_root_dir}clang/lib/Analysis/FlowSensitive/Models",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Testing",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Annotations",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "ASTOpsTest.cpp",
    "ArenaTest.cpp",
    "CFGMatchSwitchTest.cpp",
    "CachedConstAccessorsLatticeTest.cpp",
    "ChromiumCheckModelTest.cpp",
    "DataflowAnalysisContextTest.cpp",
    "DataflowEnvironmentTest.cpp",
    "DebugSupportTest.cpp",
    "DeterminismTest.cpp",
    "LoggerTest.cpp",
    "MapLatticeTest.cpp",
    "MatchSwitchTest.cpp",
    "MultiVarConstantPropagationTest.cpp",
    "RecordOpsTest.cpp",
    "SignAnalysisTest.cpp",
    "SimplifyConstraintsTest.cpp",
    "SingleVarConstantPropagationTest.cpp",
    "TestingSupport.cpp",
    "TestingSupportTest.cpp",
    "TransferBranchTest.cpp",
    "TransferTest.cpp",
    "TypeErasedDataflowAnalysisTest.cpp",
    "UncheckedOptionalAccessModelTest.cpp",
    "ValueTest.cpp",
    "WatchedLiteralsSolverTest.cpp",
  ]
}
