import("//build_overrides/llvm.gni")

llvm_static_library("Symtab") {
  output_name = "lldbPluginSymbolFileSymtab"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Symbol",
  ]
  sources = [ "SymbolFileSymtab.cpp" ]
}
