import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ObjectYAMLTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "DWARFYAMLTest.cpp",
    "DXContainerYAMLTest.cpp",
    "ELFYAMLTest.cpp",
    "MinidumpYAMLTest.cpp",
    "YAML2ObjTest.cpp",
    "YAMLTest.cpp",
  ]
}
