import("//build_overrides/llvm.gni")

llvm_executable("llvm-opt-report") {
  deps = [
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Remarks",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "OptReport.cpp" ]
}
