import("//build_overrides/llvm.gni")

llvm_executable("llvm-cfi-verify") {
  deps = [
    "lib",
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsAsmParsers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDisassemblers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
  ]
  sources = [ "llvm-cfi-verify.cpp" ]
}
