import("//build_overrides/llvm.gni")

llvm_static_library("POSIX") {
  output_name = "lldbPluginProcessPOSIX"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/Platform/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "CrashReason.cpp",
    "NativeProcessELF.cpp",
    "ProcessPOSIXLog.cpp",
  ]
}
