import("//build_overrides/llvm.gni")

llvm_static_library("ARM") {
  output_name = "lldbPluginInstructionARM"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "EmulateInstructionARM.cpp",
    "EmulationStateARM.cpp",
  ]
}
