import("//build_overrides/llvm.gni")

llvm_static_library("hicpp") {
  output_name = "clangTidyHICPPModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/bugprone",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/cppcoreguidelines",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/google",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/misc",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/modernize",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/performance",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/readability",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "ExceptionBaseclassCheck.cpp",
    "HICPPTidyModule.cpp",
    "IgnoredRemoveResultCheck.cpp",
    "MultiwayPathsCoveredCheck.cpp",
    "NoAssemblerCheck.cpp",
    "SignedBitwiseCheck.cpp",
  ]
}
