import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("JITLinkTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/ExecutionEngine/JITLink",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Shared",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/TargetProcess",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/RuntimeDyld",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "AArch32ErrorTests.cpp",
    "AArch32Tests.cpp",
    "EHFrameSupportTests.cpp",
    "JITLinkMocks.cpp",
    "LinkGraphTests.cpp",
    "MemoryManagerErrorTests.cpp",
    "StubsTests.cpp",
  ]
}
