import("//build_overrides/llvm.gni")

llvm_executable("llvm-cov") {
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/lib/Debuginfod",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ProfileData",
    "${llvm_root_dir}llvm/lib/ProfileData/Coverage",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "CodeCoverage.cpp",
    "CoverageExporterJson.cpp",
    "CoverageExporterLcov.cpp",
    "CoverageFilters.cpp",
    "CoverageReport.cpp",
    "CoverageSummaryInfo.cpp",
    "SourceCoverageView.cpp",
    "SourceCoverageViewHTML.cpp",
    "SourceCoverageViewText.cpp",
    "TestingSupport.cpp",
    "gcov.cpp",
    "llvm-cov.cpp",
  ]
}
