import("//build_overrides/llvm.gni")

llvm_static_library("DependencyScanning") {
  output_name = "clangToolingDependencyScanning"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/CodeGen",
    "${llvm_root_dir}clang/lib/Driver",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/FrontendTool",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Parse",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DependencyScanningFilesystem.cpp",
    "DependencyScanningService.cpp",
    "DependencyScanningTool.cpp",
    "DependencyScanningWorker.cpp",
    "ModuleDepCollector.cpp",
  ]
}
