import("//build_overrides/llvm.gni")

llvm_static_library("ExecutionEngine") {
  output_name = "LLVMExecutionEngine"
  public_deps = [
    # Must be a public_dep because ExecutionEngine's headers include
    # llvm-config.h.
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
  ]
  deps = [
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/TargetProcess",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ExecutionEngine.cpp",
    "ExecutionEngineBindings.cpp",
    "GDBRegistrationListener.cpp",
    "SectionMemoryManager.cpp",
    "TargetSelect.cpp",
  ]
}
