import("//build_overrides/llvm.gni")

llvm_static_library("AggressiveInstCombine") {
  output_name = "LLVMAggressiveInstCombine"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "AggressiveInstCombine.cpp",
    "TruncInstCombine.cpp",
  ]
}
