import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("FileCheckTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/FileCheck",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [ "FileCheckTest.cpp" ]
}
