import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/tools/binutils_symlinks.gni")
import("${llvm_root_dir}llvm/tools/cctools_symlinks.gni")
import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")
import("${llvm_root_dir}llvm/utils/gn/build/driver_executable.gni")
import("${llvm_root_dir}llvm/utils/gn/build/symlink_or_copy.gni")

tablegen("ObjdumpOpts") {
  visibility = [ ":llvm-objdump" ]
  args = [ "-gen-opt-parser-defs" ]
}

tablegen("OtoolOpts") {
  visibility = [ ":llvm-objdump" ]
  args = [ "-gen-opt-parser-defs" ]
}

symlinks = [ "llvm-otool" ]
if (llvm_install_binutils_symlinks) {
  symlinks += [ "objdump" ]
}
if (llvm_install_cctools_symlinks) {
  symlinks += [ "otool" ]
}

foreach(target, symlinks) {
  symlink_or_copy(target) {
    deps = [ ":llvm-objdump" ]
    source = "llvm-objdump"
    output = "$root_out_dir/bin/$target"
  }
}

# //:llvm-objdump depends on this symlink target, see comment in //BUILD.gn.
group("symlinks") {
  deps = [ ":llvm-objdump" ]
  foreach(target, symlinks) {
    deps += [ ":$target" ]
  }
}

driver_executable("llvm-objdump") {
  deps = [
    ":ObjdumpOpts",
    ":OtoolOpts",
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/DebugInfo/PDB",
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/Debuginfod",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCDisassembler",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDisassemblers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/utils/gn/build/libs/xar",
  ]
  sources = [
    "COFFDump.cpp",
    "ELFDump.cpp",
    "MachODump.cpp",
    "OffloadDump.cpp",
    "SourcePrinter.cpp",
    "WasmDump.cpp",
    "XCOFFDump.cpp",
    "llvm-objdump.cpp",
  ]
}
