import("//build_overrides/llvm.gni")

llvm_static_library("ObjCopy") {
  output_name = "LLVMObjCopy"
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ "." ]
  sources = [
    "Archive.cpp",
    "COFF/COFFObjcopy.cpp",
    "COFF/COFFObject.cpp",
    "COFF/COFFReader.cpp",
    "COFF/COFFWriter.cpp",
    "CommonConfig.cpp",
    "ConfigManager.cpp",
    "ELF/ELFObjcopy.cpp",
    "ELF/ELFObject.cpp",
    "MachO/MachOLayoutBuilder.cpp",
    "MachO/MachOObjcopy.cpp",
    "MachO/MachOObject.cpp",
    "MachO/MachOReader.cpp",
    "MachO/MachOWriter.cpp",
    "ObjCopy.cpp",
    "XCOFF/XCOFFObjcopy.cpp",
    "XCOFF/XCOFFReader.cpp",
    "XCOFF/XCOFFWriter.cpp",
    "wasm/WasmObjcopy.cpp",
    "wasm/WasmObject.cpp",
    "wasm/WasmReader.cpp",
    "wasm/WasmWriter.cpp",
  ]
}
