import("//build_overrides/llvm.gni")

llvm_static_library("Parallel") {
  output_name = "LLVMDWARFLinkerParallel"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/DWARFLinker",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AcceleratorRecordsSaver.cpp",
    "DIEAttributeCloner.cpp",
    "DWARFEmitterImpl.cpp",
    "DWARFLinker.cpp",
    "DWARFLinkerCompileUnit.cpp",
    "DWARFLinkerImpl.cpp",
    "DWARFLinkerTypeUnit.cpp",
    "DWARFLinkerUnit.cpp",
    "DependencyTracker.cpp",
    "OutputSections.cpp",
    "SyntheticTypeNameBuilder.cpp",
  ]
}
