import("//build_overrides/llvm.gni")

llvm_static_library("lib") {
  output_name = "clangIncludeCleaner"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}clang/lib/Tooling/Inclusions",
    "${llvm_root_dir}clang/lib/Tooling/Inclusions/Stdlib",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ "../include" ]
  sources = [
    "Analysis.cpp",
    "FindHeaders.cpp",
    "HTMLReport.cpp",
    "IncludeSpeller.cpp",
    "LocateSymbol.cpp",
    "Record.cpp",
    "Types.cpp",
    "WalkAST.cpp",
  ]
}
