import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("DebugInfoGSYMTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/DebugInfo/GSYM",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [ "GSYMTest.cpp" ]
}
