import("//build_overrides/llvm.gni")

llvm_static_library("objc") {
  output_name = "clangTidyObjCModule"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy/utils",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AssertEquals.cpp",
    "AvoidNSErrorInitCheck.cpp",
    "DeallocInCategoryCheck.cpp",
    "ForbiddenSubclassingCheck.cpp",
    "MissingHashCheck.cpp",
    "NSDateFormatterCheck.cpp",
    "NSInvocationArgumentLifetimeCheck.cpp",
    "ObjCTidyModule.cpp",
    "PropertyDeclarationCheck.cpp",
    "SuperSelfCheck.cpp",
  ]
}
