import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ClangDocTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-doc",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ "${llvm_root_dir}clang-tools-extra/clang-doc" ]
  sources = [
    "BitcodeTest.cpp",
    "ClangDocTest.cpp",
    "GeneratorTest.cpp",
    "HTMLGeneratorTest.cpp",
    "MDGeneratorTest.cpp",
    "MergeTest.cpp",
    "SerializeTest.cpp",
    "YAMLGeneratorTest.cpp",
  ]
}
