import("//build_overrides/llvm.gni")

llvm_static_library("Orc") {
  output_name = "LLVMOrcJIT"
  deps = [
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/JITLink",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Shared",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/TargetProcess",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/RuntimeDyld",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Passes",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/lib/WindowsDriver",
  ]
  sources = [
    "COFFPlatform.cpp",
    "COFFVCRuntimeSupport.cpp",
    "CompileOnDemandLayer.cpp",
    "CompileUtils.cpp",
    "Core.cpp",
    "DebugObjectManagerPlugin.cpp",
    "DebugUtils.cpp",
    "ELFNixPlatform.cpp",
    "EPCDebugObjectRegistrar.cpp",
    "EPCDynamicLibrarySearchGenerator.cpp",
    "EPCEHFrameRegistrar.cpp",
    "EPCGenericDylibManager.cpp",
    "EPCGenericJITLinkMemoryManager.cpp",
    "EPCGenericRTDyldMemoryManager.cpp",
    "EPCIndirectionUtils.cpp",
    "ExecutionUtils.cpp",
    "ExecutorProcessControl.cpp",
    "IRCompileLayer.cpp",
    "IRPartitionLayer.cpp",
    "IRTransformLayer.cpp",
    "IndirectionUtils.cpp",
    "JITLinkRedirectableSymbolManager.cpp",
    "JITTargetMachineBuilder.cpp",
    "LLJIT.cpp",
    "Layer.cpp",
    "LazyReexports.cpp",
    "LoadLinkableFile.cpp",
    "LookupAndRecordAddrs.cpp",
    "MachO.cpp",
    "MachOPlatform.cpp",
    "Mangling.cpp",
    "MapperJITLinkMemoryManager.cpp",
    "MemoryMapper.cpp",
    "ObjectFileInterface.cpp",
    "ObjectLinkingLayer.cpp",
    "ObjectTransformLayer.cpp",
    "OrcABISupport.cpp",
    "OrcV2CBindings.cpp",
    "RTDyldObjectLinkingLayer.cpp",
    "ReOptimizeLayer.cpp",
    "RedirectionManager.cpp",
    "SectCreate.cpp",
    "SimpleRemoteEPC.cpp",
    "SpeculateAnalyses.cpp",
    "Speculation.cpp",
    "TaskDispatch.cpp",
    "ThreadSafeModule.cpp",
  ]
}
