import("//build_overrides/llvm.gni")

llvm_static_library("Lex") {
  output_name = "clangLex"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DependencyDirectivesScanner.cpp",
    "HeaderMap.cpp",
    "HeaderSearch.cpp",
    "InitHeaderSearch.cpp",
    "Lexer.cpp",
    "LiteralSupport.cpp",
    "MacroArgs.cpp",
    "MacroInfo.cpp",
    "ModuleMap.cpp",
    "PPCaching.cpp",
    "PPCallbacks.cpp",
    "PPConditionalDirectiveRecord.cpp",
    "PPDirectives.cpp",
    "PPExpressions.cpp",
    "PPLexerChange.cpp",
    "PPMacroExpansion.cpp",
    "Pragma.cpp",
    "PreprocessingRecord.cpp",
    "Preprocessor.cpp",
    "PreprocessorLexer.cpp",
    "ScratchBuffer.cpp",
    "TokenConcatenation.cpp",
    "TokenLexer.cpp",
  ]
}
