import("//build_overrides/llvm.gni")

llvm_static_library("IPO") {
  output_name = "LLVMipo"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/Frontend/OpenMP",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRReader",
    "${llvm_root_dir}llvm/lib/Linker",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ProfileData",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/AggressiveInstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/InstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/Instrumentation",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/lib/Transforms/Vectorize",
  ]
  sources = [
    "AlwaysInliner.cpp",
    "Annotation2Metadata.cpp",
    "ArgumentPromotion.cpp",
    "Attributor.cpp",
    "AttributorAttributes.cpp",
    "BarrierNoopPass.cpp",
    "BlockExtractor.cpp",
    "CalledValuePropagation.cpp",
    "ConstantMerge.cpp",
    "CrossDSOCFI.cpp",
    "DeadArgumentElimination.cpp",
    "ElimAvailExtern.cpp",
    "EmbedBitcodePass.cpp",
    "ExpandVariadics.cpp",
    "ExtractGV.cpp",
    "ForceFunctionAttrs.cpp",
    "FunctionAttrs.cpp",
    "FunctionImport.cpp",
    "FunctionSpecialization.cpp",
    "GlobalDCE.cpp",
    "GlobalOpt.cpp",
    "GlobalSplit.cpp",
    "HotColdSplitting.cpp",
    "IPO.cpp",
    "IROutliner.cpp",
    "InferFunctionAttrs.cpp",
    "Inliner.cpp",
    "Internalize.cpp",
    "LoopExtractor.cpp",
    "LowerTypeTests.cpp",
    "MemProfContextDisambiguation.cpp",
    "MergeFunctions.cpp",
    "ModuleInliner.cpp",
    "OpenMPOpt.cpp",
    "PartialInlining.cpp",
    "SCCP.cpp",
    "SampleContextTracker.cpp",
    "SampleProfile.cpp",
    "SampleProfileMatcher.cpp",
    "SampleProfileProbe.cpp",
    "StripDeadPrototypes.cpp",
    "StripSymbols.cpp",
    "ThinLTOBitcodeWriter.cpp",
    "WholeProgramDevirt.cpp",
  ]
}
