import("//build_overrides/llvm.gni")

llvm_static_library("Debuginfod") {
  output_name = "LLVMDebuginfod"
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/utils/gn/build/libs/curl",
  ]
  sources = [
    "BuildIDFetcher.cpp",
    "Debuginfod.cpp",
    "HTTPClient.cpp",
    "HTTPServer.cpp",
  ]
}
