import("//build_overrides/llvm.gni")

import("${llvm_root_dir}clang/resource_dir.gni")

llvm_source_set("sources") {
  configs -= [ "${llvm_root_dir}llvm/utils/gn/build:llvm_code" ]
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:crt_code" ]
  sources = [ "cfi.cpp" ]
}

copy("ignorelist") {
  sources = [ "cfi_ignorelist.txt" ]
  outputs = [ "$clang_resource_dir/share/{{source_target_relative}}" ]
}
