import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("JITLoaderGDBProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("JITLoaderGDBPropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "JITLoaderGDBProperties.td"
}

llvm_static_library("GDB") {
  output_name = "lldbPluginJITLoaderGDB"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    ":JITLoaderGDBProperties",
    ":JITLoaderGDBPropertiesEnum",
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/ObjectFile/Mach-O",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/ObjectFile/Mach-O.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "JITLoaderGDB.cpp" ]
}
