import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("BasicTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "CharInfoTest.cpp",
    "DarwinSDKInfoTest.cpp",
    "DiagnosticTest.cpp",
    "FileEntryTest.cpp",
    "FileManagerTest.cpp",
    "LineOffsetMappingTest.cpp",
    "SanitizersTest.cpp",
    "SarifTest.cpp",
    "SourceManagerTest.cpp",
  ]
}
