import("//build_overrides/llvm.gni")

llvm_static_library("Passes") {
  output_name = "LLVMBOLTPasses"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:bolt_code" ]
  deps = [
    "${llvm_root_dir}bolt/lib/Core",
    "${llvm_root_dir}bolt/lib/Utils",
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/utils/gn/build/libs/pthread",
  ]
  sources = [
    "ADRRelaxationPass.cpp",
    "Aligner.cpp",
    "AllocCombiner.cpp",
    "AsmDump.cpp",
    "BinaryPasses.cpp",
    "CMOVConversion.cpp",
    "CacheMetrics.cpp",
    "ContinuityStats.cpp",
    "DataflowAnalysis.cpp",
    "DataflowInfoManager.cpp",
    "FixRISCVCallsPass.cpp",
    "FixRelaxationPass.cpp",
    "FrameAnalysis.cpp",
    "FrameOptimizer.cpp",
    "HFSort.cpp",
    "Hugify.cpp",
    "IdenticalCodeFolding.cpp",
    "IndirectCallPromotion.cpp",
    "Inliner.cpp",
    "Instrumentation.cpp",
    "JTFootprintReduction.cpp",
    "LivenessAnalysis.cpp",
    "LongJmp.cpp",
    "LoopInversionPass.cpp",
    "MCF.cpp",
    "PLTCall.cpp",
    "PatchEntries.cpp",
    "PettisAndHansen.cpp",
    "RegAnalysis.cpp",
    "RegReAssign.cpp",
    "ReorderAlgorithm.cpp",
    "ReorderData.cpp",
    "ReorderFunctions.cpp",
    "RetpolineInsertion.cpp",
    "ShrinkWrapping.cpp",
    "SplitFunctions.cpp",
    "StackAllocationAnalysis.cpp",
    "StackAvailableExpressions.cpp",
    "StackPointerTracking.cpp",
    "StackReachingUses.cpp",
    "StokeInfo.cpp",
    "TailDuplication.cpp",
    "ThreeWayBranch.cpp",
    "ValidateInternalCalls.cpp",
    "ValidateMemRefs.cpp",
    "VeneerElimination.cpp",
  ]
}
