import("//build_overrides/llvm.gni")

llvm_static_library("None") {
  output_name = "lldbPluginScriptInterpreterNone"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Interpreter",
  ]
  sources = [ "ScriptInterpreterNone.cpp" ]
}
