import("//build_overrides/llvm.gni")

llvm_static_library("Mach-O-Fileset") {
  output_name = "lldbPluginObjectContainerMachOFileset"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
  ]
  sources = [ "ObjectContainerMachOFileset.cpp" ]
}
