import("//build_overrides/llvm.gni")

llvm_static_library("Core") {
  output_name = "LLVMBOLTCore"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:bolt_code" ]
  deps = [
    "${llvm_root_dir}bolt/lib/Utils",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen/AsmPrinter",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCDisassembler",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/utils/gn/build/libs/pthread",
  ]
  sources = [
    "AddressMap.cpp",
    "BinaryBasicBlock.cpp",
    "BinaryContext.cpp",
    "BinaryData.cpp",
    "BinaryEmitter.cpp",
    "BinaryFunction.cpp",
    "BinaryFunctionCallGraph.cpp",
    "BinaryFunctionProfile.cpp",
    "BinarySection.cpp",
    "CallGraph.cpp",
    "CallGraphWalker.cpp",
    "DIEBuilder.cpp",
    "DebugData.cpp",
    "DebugNames.cpp",
    "DynoStats.cpp",
    "Exceptions.cpp",
    "FunctionLayout.cpp",
    "GDBIndex.cpp",
    "HashUtilities.cpp",
    "JumpTable.cpp",
    "MCPlusBuilder.cpp",
    "ParallelUtilities.cpp",
    "Relocation.cpp",
  ]
}
