import("//build_overrides/llvm.gni")

import("${llvm_root_dir}compiler-rt/target.gni")

llvm_source_set("sources") {
  configs -= [ "${llvm_root_dir}llvm/utils/gn/build:llvm_code" ]
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:crt_code" ]
}

llvm_static_library("ubsan_minimal") {
  output_dir = crt_current_out_dir
  output_name = "clang_rt.ubsan_minimal$crt_current_target_suffix"
  complete_static_lib = true
  configs -= [
    "${llvm_root_dir}llvm/utils/gn/build:llvm_code",
    "${llvm_root_dir}llvm/utils/gn/build:thin_archive",
  ]
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:crt_code" ]
  sources = [ "ubsan_minimal_handlers.cpp" ]
  defines = [ "SANITIZER_COMMON_NO_REDEFINE_BUILTINS" ]
}
