import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/lib/Target/targets.gni")
import("${llvm_root_dir}llvm/utils/gn/build/toolchain/compiler.gni")

supported_toolchains = [ "${llvm_root_dir}llvm/utils/gn/build/toolchain:stage2_unix" ] +
                       supported_android_toolchains

group("libunwind") {
  deps = []
  foreach(toolchain, supported_toolchains) {
    deps += [ "${llvm_root_dir}libunwind/src($toolchain)" ]
  }
}
