import("//build_overrides/llvm.gni")

llvm_executable("c-index-test") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/include/clang/Config",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/CodeGen",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Index",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/tools/libclang",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/utils/gn/build/libs/xml",
  ]
  if (host_os != "win") {
    cflags_c = [ "-std=gnu89" ]
  }
  sources = [
    "c-index-test.c",
    "core_main.cpp",
  ]

  # See comment at top of clang/tools/libclang/BUILD.gn for why this isn't
  # needed on Linux.
  if (host_os == "mac") {
    ldflags = [ "-Wl,-rpath,@loader_path/../lib" ]
  }
}
