import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")

tablegen("Options") {
  visibility = [ ":COFF" ]
  args = [ "-gen-opt-parser-defs" ]
}

llvm_static_library("COFF") {
  output_name = "lldCOFF"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lld_code" ]
  deps = [
    ":Options",
    "${llvm_root_dir}lld/Common",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/DebugInfo/MSF",
    "${llvm_root_dir}llvm/lib/DebugInfo/PDB",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/LTO",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/ToolDrivers/llvm-lib:LibDriver",
    "${llvm_root_dir}llvm/lib/WindowsDriver",
    "${llvm_root_dir}llvm/lib/WindowsManifest",
  ]
  sources = [
    "COFFLinkerContext.cpp",
    "CallGraphSort.cpp",
    "Chunks.cpp",
    "DLL.cpp",
    "DebugTypes.cpp",
    "Driver.cpp",
    "DriverUtils.cpp",
    "ICF.cpp",
    "InputFiles.cpp",
    "LLDMapFile.cpp",
    "LTO.cpp",
    "MapFile.cpp",
    "MarkLive.cpp",
    "MinGW.cpp",
    "PDB.cpp",
    "SymbolTable.cpp",
    "Symbols.cpp",
    "Writer.cpp",
  ]
}
