import("//build_overrides/llvm.gni")

llvm_executable("llvm-lto2") {
  deps = [
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/LTO",
    "${llvm_root_dir}llvm/lib/Linker",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [ "llvm-lto2.cpp" ]
}
