import("//build_overrides/llvm.gni")

llvm_static_library("ItaniumABI") {
  output_name = "lldbPluginCXXItaniumABI"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/CPlusPlus",
    "${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
  ]

  # Reaches into Plugins/LanguageRuntime/CPlusPlus.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "ItaniumABILanguageRuntime.cpp" ]
}
