import("//build_overrides/llvm.gni")

llvm_static_library("POSIX-DYLD") {
  output_name = "lldbPluginDynamicLoaderPosixDYLD"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",

    #"${llvm_root_dir}lldb/source/Plugins/Process/elf-core", # Dependency cycle.
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "DYLDRendezvous.cpp",
    "DynamicLoaderPOSIXDYLD.cpp",
  ]
}
