import("//build_overrides/llvm.gni")

llvm_static_library("gdb-server") {
  output_name = "lldbPluginPlatformGDB"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",

    #"${llvm_root_dir}lldb/source/Plugins/Process/gdb-remote",  # 4-deep dependency cycle
    "${llvm_root_dir}lldb/source/Target",
  ]

  # Reaches into Plugins/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "PlatformRemoteGDBServer.cpp" ]
}
