import("//build_overrides/llvm.gni")

llvm_static_library("GlobalISel") {
  output_name = "LLVMGlobalISel"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
  ]
  sources = [
    "CSEInfo.cpp",
    "CSEMIRBuilder.cpp",
    "CallLowering.cpp",
    "Combiner.cpp",
    "CombinerHelper.cpp",
    "CombinerHelperCasts.cpp",
    "CombinerHelperCompares.cpp",
    "CombinerHelperVectorOps.cpp",
    "GIMatchTableExecutor.cpp",
    "GISelChangeObserver.cpp",
    "GISelKnownBits.cpp",
    "GlobalISel.cpp",
    "IRTranslator.cpp",
    "InlineAsmLowering.cpp",
    "InstructionSelect.cpp",
    "InstructionSelector.cpp",
    "LegacyLegalizerInfo.cpp",
    "LegalityPredicates.cpp",
    "LegalizeMutations.cpp",
    "Legalizer.cpp",
    "LegalizerHelper.cpp",
    "LegalizerInfo.cpp",
    "LoadStoreOpt.cpp",
    "Localizer.cpp",
    "LostDebugLocObserver.cpp",
    "MachineIRBuilder.cpp",
    "RegBankSelect.cpp",
    "Utils.cpp",
  ]
}
