import("//build_overrides/llvm.gni")

llvm_static_library("NativePDB") {
  output_name = "lldbPluginSymbolFileNativePDB"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Plugins/ObjectFile/PDB",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Utility",

    #"${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang", # 3-hop dependency cycle.
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/DebugInfo/PDB",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  # Reaches into Plugins/ExpressionParser.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "CodeViewRegisterMapping.cpp",
    "CompileUnitIndex.cpp",
    "DWARFLocationExpression.cpp",
    "PdbAstBuilder.cpp",
    "PdbFPOProgramToDWARFExpression.cpp",
    "PdbIndex.cpp",
    "PdbSymUid.cpp",
    "PdbUtil.cpp",
    "SymbolFileNativePDB.cpp",
    "UdtRecordCompleter.cpp",
  ]
}
