import("//build_overrides/llvm.gni")

llvm_static_library("ObjC") {
  output_name = "lldbPluginObjCRuntime"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
  ]

  # Reaches into Plugins/TypeSystem/Clang.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "ObjCLanguageRuntime.cpp" ]
}
