import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("LexTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Parse",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Annotations",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "DependencyDirectivesScannerTest.cpp",
    "HeaderMapTest.cpp",
    "HeaderSearchTest.cpp",
    "LexerTest.cpp",
    "ModuleDeclStateTest.cpp",
    "PPCallbacksTest.cpp",
    "PPConditionalDirectiveRecordTest.cpp",
    "PPDependencyDirectivesTest.cpp",
    "PPMemoryAllocationsTest.cpp",
  ]
}
