import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ClangDriverTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Driver",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DXCModeTest.cpp",
    "DistroTest.cpp",
    "GCCVersionTest.cpp",
    "ModuleCacheTest.cpp",
    "MultilibBuilderTest.cpp",
    "MultilibTest.cpp",
    "SanitizerArgsTest.cpp",
    "ToolChainTest.cpp",
  ]
}
