import("//build_overrides/llvm.gni")

llvm_executable("llvm-pdbutil") {
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/DebugInfo/MSF",
    "${llvm_root_dir}llvm/lib/DebugInfo/PDB",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "BytesOutputStyle.cpp",
    "DumpOutputStyle.cpp",
    "ExplainOutputStyle.cpp",
    "MinimalSymbolDumper.cpp",
    "MinimalTypeDumper.cpp",
    "PdbYaml.cpp",
    "PrettyBuiltinDumper.cpp",
    "PrettyClassDefinitionDumper.cpp",
    "PrettyClassLayoutGraphicalDumper.cpp",
    "PrettyCompilandDumper.cpp",
    "PrettyEnumDumper.cpp",
    "PrettyExternalSymbolDumper.cpp",
    "PrettyFunctionDumper.cpp",
    "PrettyTypeDumper.cpp",
    "PrettyTypedefDumper.cpp",
    "PrettyVariableDumper.cpp",
    "StreamUtil.cpp",
    "TypeReferenceTracker.cpp",
    "YAMLOutputStyle.cpp",
    "llvm-pdbutil.cpp",
  ]
}
