import("//build_overrides/llvm.gni")

llvm_static_library("RuntimeLibs") {
  output_name = "LLVMBOLTRuntimeLibs"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:bolt_code" ]
  deps = [
    "${llvm_root_dir}bolt/include/bolt/RuntimeLibs:RuntimeLibraryVariables",
    "${llvm_root_dir}bolt/lib/Core",
    "${llvm_root_dir}bolt/lib/Passes",
    "${llvm_root_dir}bolt/lib/Utils",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/JITLink",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [ target_gen_dir ]
  sources = [
    "HugifyRuntimeLibrary.cpp",
    "InstrumentationRuntimeLibrary.cpp",
    "RuntimeLibrary.cpp",
  ]

  # FIXME: Hopefully change this, see
  # https://github.com/llvm/llvm-project/pull/97130/files#r1691863361
  defines = [ "CMAKE_INSTALL_FULL_LIBDIR=\"\"" ]
}
