import("//build_overrides/llvm.gni")

llvm_static_library("Breakpad") {
  output_name = "lldbPluginSymbolFileBreakpad"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/ObjectFile/Breakpad",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/SymbolFile/Breakpad.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "SymbolFileBreakpad.cpp" ]
}
