import("//build_overrides/llvm.gni")

llvm_static_library("Passes") {
  output_name = "LLVMPasses"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/IRPrinter",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/Transforms/AggressiveInstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/CFGuard",
    "${llvm_root_dir}llvm/lib/Transforms/Coroutines",
    "${llvm_root_dir}llvm/lib/Transforms/HipStdPar",
    "${llvm_root_dir}llvm/lib/Transforms/IPO",
    "${llvm_root_dir}llvm/lib/Transforms/InstCombine",
    "${llvm_root_dir}llvm/lib/Transforms/Instrumentation",
    "${llvm_root_dir}llvm/lib/Transforms/ObjCARC",
    "${llvm_root_dir}llvm/lib/Transforms/Scalar",
    "${llvm_root_dir}llvm/lib/Transforms/Utils",
    "${llvm_root_dir}llvm/lib/Transforms/Vectorize",
  ]
  sources = [
    "CodeGenPassBuilder.cpp",
    "OptimizationLevel.cpp",
    "PassBuilder.cpp",
    "PassBuilderBindings.cpp",
    "PassBuilderPipelines.cpp",
    "PassPlugin.cpp",
    "StandardInstrumentations.cpp",
  ]
}
