import("//build_overrides/llvm.gni")

llvm_static_library("elf-core") {
  output_name = "lldbPluginProcessElfCore"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Plugins/DynamicLoader/POSIX-DYLD",
    "${llvm_root_dir}lldb/source/Plugins/ObjectFile/ELF",
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/DynamicLoader/POSIX-DYLD.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "ProcessElfCore.cpp",
    "RegisterContextLinuxCore_x86_64.cpp",
    "RegisterContextPOSIXCore_arm.cpp",
    "RegisterContextPOSIXCore_arm64.cpp",
    "RegisterContextPOSIXCore_mips64.cpp",
    "RegisterContextPOSIXCore_powerpc.cpp",
    "RegisterContextPOSIXCore_ppc64le.cpp",
    "RegisterContextPOSIXCore_riscv64.cpp",
    "RegisterContextPOSIXCore_s390x.cpp",
    "RegisterContextPOSIXCore_x86_64.cpp",
    "RegisterUtilities.cpp",
    "ThreadElfCore.cpp",
  ]
}
