import("//build_overrides/llvm.gni")

llvm_static_library("BinaryFormat") {
  output_name = "LLVMBinaryFormat"
  deps = [
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "AMDGPUMetadataVerifier.cpp",
    "COFF.cpp",
    "DXContainer.cpp",
    "Dwarf.cpp",
    "ELF.cpp",
    "MachO.cpp",
    "Magic.cpp",
    "Minidump.cpp",
    "MsgPackDocument.cpp",
    "MsgPackDocumentYAML.cpp",
    "MsgPackReader.cpp",
    "MsgPackWriter.cpp",
    "Wasm.cpp",
    "XCOFF.cpp",
  ]
}
