import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ObjCopyTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/ObjCopy",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [ "ObjCopyTest.cpp" ]
}
