import("//build_overrides/llvm.gni")

import("${llvm_root_dir}clang-tools-extra/clangd/quality/gen_decision_forest.gni")
import("${llvm_root_dir}third-party/unittest/unittest.gni")

gen_decision_forest("DecisionForestRuntimeTest") {
  model = "decision_forest_model"
  filename = "DecisionForestRuntimeTest"
  cpp_class = "::ns1::ns2::test::Example"
}

unittest("ClangdTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    ":DecisionForestRuntimeTest",
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clangd",
    "${llvm_root_dir}clang-tools-extra/clangd:features",
    "${llvm_root_dir}clang-tools-extra/clangd/refactor/tweaks",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Index",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Testing",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}clang/lib/Tooling/Inclusions",
    "${llvm_root_dir}clang/lib/Tooling/Syntax",
    "${llvm_root_dir}llvm/include/llvm/Config:llvm-config",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Annotations",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  include_dirs = [
    ".",
    "${llvm_root_dir}clang-tools-extra/clangd",

    # For "clang-include-cleaner/..." includes.
    "${llvm_root_dir}clang-tools-extra/include-cleaner/include",

    # To pick up the generated inc files.
    "$target_gen_dir/../../clangd/tool",

    # To pick up the generated DecisionForestRuntimeTest.h file.
    target_gen_dir,
  ]
  sources = [
    "ASTSignalsTests.cpp",
    "ASTTests.cpp",
    "Annotations.cpp",
    "BackgroundIndexTests.cpp",
    "CallHierarchyTests.cpp",
    "CanonicalIncludesTests.cpp",
    "ClangdLSPServerTests.cpp",
    "ClangdTests.cpp",
    "CodeCompleteTests.cpp",
    "CodeCompletionStringsTests.cpp",
    "CollectMacrosTests.cpp",
    "CompileCommandsTests.cpp",
    "CompilerTests.cpp",
    "ConfigCompileTests.cpp",
    "ConfigProviderTests.cpp",
    "ConfigYAMLTests.cpp",
    "DecisionForestTests.cpp",
    "DexTests.cpp",
    "DiagnosticsTests.cpp",
    "DraftStoreTests.cpp",
    "DumpASTTests.cpp",
    "ExpectedTypeTest.cpp",
    "FSTests.cpp",
    "FeatureModulesTests.cpp",
    "FileDistanceTests.cpp",
    "FileIndexTests.cpp",
    "FindSymbolsTests.cpp",
    "FindTargetTests.cpp",
    "FormatTests.cpp",
    "FuzzyMatchTests.cpp",
    "GlobalCompilationDatabaseTests.cpp",
    "HeaderSourceSwitchTests.cpp",
    "HeadersTests.cpp",
    "HoverTests.cpp",
    "IncludeCleanerTests.cpp",
    "IndexActionTests.cpp",
    "IndexTests.cpp",
    "InlayHintTests.cpp",
    "InsertionPointTests.cpp",
    "JSONTransportTests.cpp",
    "LSPBinderTests.cpp",
    "LSPClient.cpp",
    "LoggerTests.cpp",
    "ModulesTests.cpp",
    "ParsedASTTests.cpp",
    "PathMappingTests.cpp",
    "PreambleTests.cpp",
    "PrerequisiteModulesTest.cpp",
    "PrintASTTests.cpp",
    "ProjectAwareIndexTests.cpp",
    "QualityTests.cpp",
    "RIFFTests.cpp",
    "RenameTests.cpp",
    "ReplayPeambleTests.cpp",
    "SelectionTests.cpp",
    "SemanticHighlightingTests.cpp",
    "SemanticSelectionTests.cpp",
    "SerializationTests.cpp",
    "SourceCodeTests.cpp",
    "StdLibTests.cpp",
    "SymbolCollectorTests.cpp",
    "SymbolInfoTests.cpp",
    "SyncAPI.cpp",
    "TUSchedulerTests.cpp",
    "TestFS.cpp",
    "TestIndex.cpp",
    "TestTU.cpp",
    "TestWorkspace.cpp",
    "ThreadCrashReporterTests.cpp",
    "TidyProviderTests.cpp",
    "TypeHierarchyTests.cpp",
    "URITests.cpp",
    "XRefsTests.cpp",
    "support/CancellationTests.cpp",
    "support/ContextTests.cpp",
    "support/FileCacheTests.cpp",
    "support/FunctionTests.cpp",
    "support/MarkupTests.cpp",
    "support/MemoryTreeTests.cpp",
    "support/PathTests.cpp",
    "support/TestTracer.cpp",
    "support/ThreadingTests.cpp",
    "support/TraceTests.cpp",
    "tweaks/AddUsingTests.cpp",
    "tweaks/AnnotateHighlightingsTests.cpp",
    "tweaks/DefineInlineTests.cpp",
    "tweaks/DefineOutlineTests.cpp",
    "tweaks/DumpASTTests.cpp",
    "tweaks/DumpRecordLayoutTests.cpp",
    "tweaks/DumpSymbolTests.cpp",
    "tweaks/ExpandDeducedTypeTests.cpp",
    "tweaks/ExpandMacroTests.cpp",
    "tweaks/ExtractFunctionTests.cpp",
    "tweaks/ExtractVariableTests.cpp",
    "tweaks/MemberwiseConstructorTests.cpp",
    "tweaks/ObjCLocalizeStringLiteralTests.cpp",
    "tweaks/ObjCMemberwiseInitializerTests.cpp",
    "tweaks/PopulateSwitchTests.cpp",
    "tweaks/RawStringLiteralTests.cpp",
    "tweaks/RemoveUsingNamespaceTests.cpp",
    "tweaks/ScopifyEnumTests.cpp",
    "tweaks/ShowSelectionTreeTests.cpp",
    "tweaks/SpecialMembersTests.cpp",
    "tweaks/SwapBinaryOperandsTests.cpp",
    "tweaks/SwapIfBranchesTests.cpp",
    "tweaks/TweakTesting.cpp",
    "tweaks/TweakTests.cpp",
  ]
}
