import("//build_overrides/llvm.gni")

llvm_static_library("Serialization") {
  output_name = "clangSerialization"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/include/clang/Serialization:AttrPCHRead",
    "${llvm_root_dir}clang/include/clang/Serialization:AttrPCHWrite",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ASTCommon.cpp",
    "ASTCommon.h",
    "ASTReader.cpp",
    "ASTReaderDecl.cpp",
    "ASTReaderInternals.h",
    "ASTReaderStmt.cpp",
    "ASTWriter.cpp",
    "ASTWriterDecl.cpp",
    "ASTWriterStmt.cpp",
    "GeneratePCH.cpp",
    "GlobalModuleIndex.cpp",
    "InMemoryModuleCache.cpp",
    "ModuleFile.cpp",
    "ModuleFileExtension.cpp",
    "ModuleManager.cpp",
    "ObjectFilePCHContainerReader.cpp",
    "PCHContainerOperations.cpp",
  ]
}
