import("//build_overrides/llvm.gni")

llvm_static_library("CPlusPlus") {
  output_name = "lldbPluginCPlusPlusLanguage"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/DataFormatters",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/Language/ClangCommon",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/CPlusPlus",
    "${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/Language/ClangCommon.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "BlockPointer.cpp",
    "CPlusPlusLanguage.cpp",
    "CPlusPlusNameParser.cpp",
    "Coroutines.cpp",
    "CxxStringTypes.cpp",
    "GenericBitset.cpp",
    "GenericOptional.cpp",
    "LibCxx.cpp",
    "LibCxxAtomic.cpp",
    "LibCxxInitializerList.cpp",
    "LibCxxList.cpp",
    "LibCxxMap.cpp",
    "LibCxxProxyArray.cpp",
    "LibCxxQueue.cpp",
    "LibCxxRangesRefView.cpp",
    "LibCxxSliceArray.cpp",
    "LibCxxSpan.cpp",
    "LibCxxTuple.cpp",
    "LibCxxUnorderedMap.cpp",
    "LibCxxValarray.cpp",
    "LibCxxVariant.cpp",
    "LibCxxVector.cpp",
    "LibStdcpp.cpp",
    "LibStdcppTuple.cpp",
    "LibStdcppUniquePointer.cpp",
    "MSVCUndecoratedNameParser.cpp",
  ]
}
