import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("LLVMExegesisPowerPCTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/Symbolize",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target/PowerPC",

    # Exegesis reaches inside the Target/PowerPC tablegen internals and must
    # depend on these Target/PowerPC-internal build targets.
    "${llvm_root_dir}llvm/lib/Target/PowerPC/MCTargetDesc",
    "${llvm_root_dir}llvm/tools/llvm-exegesis/lib",
    "${llvm_root_dir}llvm/tools/llvm-exegesis/lib/PowerPC",
  ]
  include_dirs = [
    "${llvm_root_dir}llvm/lib/Target/PowerPC",
    "${llvm_root_dir}llvm/tools/llvm-exegesis/lib",
  ]
  sources = [
    "AnalysisTest.cpp",
    "SnippetGeneratorTest.cpp",
    "TargetTest.cpp",
  ]
}
