import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("ProcessGDBRemoteProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("ProcessGDBRemotePropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "ProcessGDBRemoteProperties.td"
}

llvm_static_library("gdb-remote") {
  output_name = "lldbPluginProcessGDBRemote"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    ":ProcessGDBRemoteProperties",
    ":ProcessGDBRemotePropertiesEnum",
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/DataFormatters",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/Platform/MacOSX",
    "${llvm_root_dir}lldb/source/Plugins/Process/Utility",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  # XXX if (have_libcompression) { deps += [ compression } }
  # Reaches into Plugins/Process/Utility.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "GDBRemoteClientBase.cpp",
    "GDBRemoteCommunication.cpp",
    "GDBRemoteCommunicationClient.cpp",
    "GDBRemoteCommunicationHistory.cpp",
    "GDBRemoteCommunicationServer.cpp",
    "GDBRemoteCommunicationServerCommon.cpp",
    "GDBRemoteCommunicationServerLLGS.cpp",
    "GDBRemoteCommunicationServerPlatform.cpp",
    "GDBRemoteRegisterContext.cpp",
    "GDBRemoteRegisterFallback.cpp",
    "ProcessGDBRemote.cpp",
    "ProcessGDBRemoteLog.cpp",
    "ThreadGDBRemote.cpp",
  ]
}
