import("//build_overrides/llvm.gni")

llvm_static_library("LogicalView") {
  output_name = "LLVMDebugInfoLogicalView"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/DebugInfo/PDB",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "Core/LVCompare.cpp",
    "Core/LVElement.cpp",
    "Core/LVLine.cpp",
    "Core/LVLocation.cpp",
    "Core/LVObject.cpp",
    "Core/LVOptions.cpp",
    "Core/LVRange.cpp",
    "Core/LVReader.cpp",
    "Core/LVScope.cpp",
    "Core/LVSort.cpp",
    "Core/LVSupport.cpp",
    "Core/LVSymbol.cpp",
    "Core/LVType.cpp",
    "LVReaderHandler.cpp",
    "Readers/LVBinaryReader.cpp",
    "Readers/LVCodeViewReader.cpp",
    "Readers/LVCodeViewVisitor.cpp",
    "Readers/LVDWARFReader.cpp",
  ]
}
