import("//build_overrides/llvm.gni")

llvm_static_library("DWP") {
  output_name = "LLVMDWP"
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
  ]
  sources = [
    "DWP.cpp",
    "DWPError.cpp",
  ]
}
