import("//build_overrides/llvm.gni")

llvm_static_library("Breakpoint") {
  output_name = "lldbBreakpoint"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/include/lldb/Host:Config",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "Breakpoint.cpp",
    "BreakpointID.cpp",
    "BreakpointIDList.cpp",
    "BreakpointList.cpp",
    "BreakpointLocation.cpp",
    "BreakpointLocationCollection.cpp",
    "BreakpointLocationList.cpp",
    "BreakpointName.cpp",
    "BreakpointOptions.cpp",
    "BreakpointPrecondition.cpp",
    "BreakpointResolver.cpp",
    "BreakpointResolverAddress.cpp",
    "BreakpointResolverFileLine.cpp",
    "BreakpointResolverFileRegex.cpp",
    "BreakpointResolverName.cpp",
    "BreakpointResolverScripted.cpp",
    "BreakpointSite.cpp",
    "StopPointSiteList.cpp",
    "Stoppoint.cpp",
    "StoppointCallbackContext.cpp",
    "StoppointSite.cpp",
    "Watchpoint.cpp",
    "WatchpointAlgorithms.cpp",
    "WatchpointList.cpp",
    "WatchpointOptions.cpp",
    "WatchpointResource.cpp",
  ]
}
