import("//build_overrides/llvm.gni")

import("${llvm_root_dir}lldb/utils/TableGen/lldb_tablegen.gni")

lldb_tablegen("PlatformMacOSXProperties") {
  args = [ "-gen-lldb-property-defs" ]
}

lldb_tablegen("PlatformMacOSXPropertiesEnum") {
  args = [ "-gen-lldb-property-enum-defs" ]
  td_file = "PlatformMacOSXProperties.td"
}

llvm_static_library("MacOSX") {
  output_name = "lldbPluginPlatformMacOSX"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    ":PlatformMacOSXProperties",
    ":PlatformMacOSXPropertiesEnum",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/DynamicLoader/Darwin-Kernel",
    "${llvm_root_dir}lldb/source/Plugins/ObjectContainer/Mach-O-Fileset",
    "${llvm_root_dir}lldb/source/Plugins/Platform/POSIX",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  # Reaches into Plugins/Platform/POSIX.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "PlatformDarwin.cpp",
    "PlatformDarwinDevice.cpp",
    "PlatformDarwinKernel.cpp",
    "PlatformMacOSX.cpp",
    "PlatformRemoteAppleBridge.cpp",
    "PlatformRemoteAppleTV.cpp",
    "PlatformRemoteAppleWatch.cpp",
    "PlatformRemoteAppleXR.cpp",
    "PlatformRemoteDarwinDevice.cpp",
    "PlatformRemoteMacOSX.cpp",
    "PlatformRemoteiOS.cpp",
  ]
  if (host_os == "mac") {
    deps += [ "objcxx" ]
    sources += [ "PlatformAppleSimulator.cpp" ]
  }
}
