import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")

tablegen("MipsGenExegesis") {
  args = [ "-gen-exegesis" ]
  td_file = "${llvm_root_dir}llvm/lib/Target/Mips/Mips.td"
}

llvm_static_library("Mips") {
  output_name = "LLVMExegesisMips"
  deps = [
    ":MipsGenExegesis",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/TargetParser",

    # Exegesis reaches inside the Target/Mips tablegen internals and must
    # depend on these Target/Mips-internal build targets.
    "${llvm_root_dir}llvm/lib/Target/Mips/MCTargetDesc",
  ]
  sources = [ "Target.cpp" ]
  include_dirs = [ "${llvm_root_dir}llvm/lib/Target/Mips" ]
}
