import("//build_overrides/llvm.gni")

llvm_executable("clang-tidy") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-tidy",
    "${llvm_root_dir}clang-tools-extra/clang-tidy:all-checks",
    "${llvm_root_dir}clang-tools-extra/clang-tidy:clang-tidy-config",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsAsmParsers",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsDescs",
    "${llvm_root_dir}llvm/lib/Target:AllTargetsInfos",
  ]
  sources = [
    "ClangTidyMain.cpp",
    "ClangTidyToolMain.cpp",
  ]
}
