import("//build_overrides/llvm.gni")

llvm_static_library("Clang") {
  output_name = "lldbPluginTypeSystemClang"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Plugins/ExpressionParser/Clang",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/ObjC",
    "${llvm_root_dir}lldb/source/Plugins/SymbolFile/DWARF",
    "${llvm_root_dir}lldb/source/Plugins/SymbolFile/PDB",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/ExpressionParser/Clang.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "TypeSystemClang.cpp" ]
}
