import("//build_overrides/llvm.gni")

llvm_static_library("Format") {
  output_name = "clangFormat"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}clang/lib/Tooling/Inclusions",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "AffectedRangeManager.cpp",
    "BreakableToken.cpp",
    "ContinuationIndenter.cpp",
    "DefinitionBlockSeparator.cpp",
    "Format.cpp",
    "FormatToken.cpp",
    "FormatTokenLexer.cpp",
    "IntegerLiteralSeparatorFixer.cpp",
    "MacroCallReconstructor.cpp",
    "MacroExpander.cpp",
    "MatchFilePath.cpp",
    "NamespaceEndCommentsFixer.cpp",
    "ObjCPropertyAttributeOrderFixer.cpp",
    "QualifierAlignmentFixer.cpp",
    "SortJavaScriptImports.cpp",
    "TokenAnalyzer.cpp",
    "TokenAnnotator.cpp",
    "UnwrappedLineFormatter.cpp",
    "UnwrappedLineParser.cpp",
    "UsingDeclarationsSorter.cpp",
    "WhitespaceManager.cpp",
  ]
}
