import("//build_overrides/llvm.gni")

llvm_static_library("Driver") {
  output_name = "LLVMFrontendDriver"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [ "CodeGenOptions.cpp" ]
}
