import("//build_overrides/llvm.gni")

llvm_static_library("DWARF") {
  output_name = "LLVMDebugInfoDWARF"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DWARFAbbreviationDeclaration.cpp",
    "DWARFAcceleratorTable.cpp",
    "DWARFAddressRange.cpp",
    "DWARFCompileUnit.cpp",
    "DWARFContext.cpp",
    "DWARFDataExtractor.cpp",
    "DWARFDebugAbbrev.cpp",
    "DWARFDebugAddr.cpp",
    "DWARFDebugArangeSet.cpp",
    "DWARFDebugAranges.cpp",
    "DWARFDebugFrame.cpp",
    "DWARFDebugInfoEntry.cpp",
    "DWARFDebugLine.cpp",
    "DWARFDebugLoc.cpp",
    "DWARFDebugMacro.cpp",
    "DWARFDebugPubTable.cpp",
    "DWARFDebugRangeList.cpp",
    "DWARFDebugRnglists.cpp",
    "DWARFDie.cpp",
    "DWARFExpression.cpp",
    "DWARFFormValue.cpp",
    "DWARFGdbIndex.cpp",
    "DWARFListTable.cpp",
    "DWARFLocationExpression.cpp",
    "DWARFTypeUnit.cpp",
    "DWARFUnit.cpp",
    "DWARFUnitIndex.cpp",
    "DWARFVerifier.cpp",
  ]
}
