import("//build_overrides/llvm.gni")

llvm_static_library("find-all-symbols") {
  output_name = "findAllSymbols"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/ASTMatchers",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "FindAllMacros.cpp",
    "FindAllSymbols.cpp",
    "FindAllSymbolsAction.cpp",
    "HeaderMapCollector.cpp",
    "PathConfig.cpp",
    "PragmaCommentHandler.cpp",
    "STLPostfixHeaderMap.cpp",
    "SymbolInfo.cpp",
  ]
}
