import("//build_overrides/llvm.gni")

llvm_static_library("AppleObjCRuntime") {
  output_name = "lldbPluginAppleObjCRuntime"
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins/ExpressionParser/Clang",
    "${llvm_root_dir}lldb/source/Plugins/LanguageRuntime/CPlusPlus",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",

    #"${llvm_root_dir}lldb/source/Plugins/TypeSystem/Clang", # 4-hop dependency cycle.
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # Reaches into Plugins/ExpressionParser/Clang.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "AppleObjCClassDescriptorV2.cpp",
    "AppleObjCDeclVendor.cpp",
    "AppleObjCRuntime.cpp",
    "AppleObjCRuntimeV1.cpp",
    "AppleObjCRuntimeV2.cpp",
    "AppleObjCTrampolineHandler.cpp",
    "AppleObjCTypeEncodingParser.cpp",
    "AppleThreadPlanStepThroughObjCTrampoline.cpp",
  ]
}
