import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ClangIncludeFixerTests") {
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-include-fixer",
    "${llvm_root_dir}clang-tools-extra/clang-include-fixer/find-all-symbols",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Format",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}clang/lib/Serialization",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}clang/lib/Tooling/Core",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  include_dirs = [
    "${llvm_root_dir}clang-tools-extra/clang-include-fixer",

    # We'd like clang/unittests/Tooling/RewriterTestContext.h in the test.
    "${llvm_root_dir}clang",
  ]
  sources = [
    "FuzzySymbolIndexTests.cpp",
    "IncludeFixerTest.cpp",
  ]
}
