import("//build_overrides/llvm.gni")

llvm_static_library("TargetProcess") {
  output_name = "LLVMOrcTargetProcess"
  deps = [
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Shared",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ExecutorSharedMemoryMapperService.cpp",
    "JITLoaderGDB.cpp",
    "JITLoaderPerf.cpp",
    "JITLoaderVTune.cpp",
    "OrcRTBootstrap.cpp",
    "RegisterEHFrames.cpp",
    "SimpleExecutorDylibManager.cpp",
    "SimpleExecutorMemoryManager.cpp",
    "SimpleRemoteEPCServer.cpp",
    "TargetExecutionUtils.cpp",
  ]
  if (current_os == "linux") {
    libs = [ "rt" ]
  }
}
