import("//build_overrides/llvm.gni")

llvm_static_library("ObjectYAML") {
  output_name = "LLVMObjectYAML"
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "ArchiveEmitter.cpp",
    "ArchiveYAML.cpp",
    "COFFEmitter.cpp",
    "COFFYAML.cpp",
    "CodeViewYAMLDebugSections.cpp",
    "CodeViewYAMLSymbols.cpp",
    "CodeViewYAMLTypeHashing.cpp",
    "CodeViewYAMLTypes.cpp",
    "DWARFEmitter.cpp",
    "DWARFYAML.cpp",
    "DXContainerEmitter.cpp",
    "DXContainerYAML.cpp",
    "ELFEmitter.cpp",
    "ELFYAML.cpp",
    "GOFFEmitter.cpp",
    "GOFFYAML.cpp",
    "MachOEmitter.cpp",
    "MachOYAML.cpp",
    "MinidumpEmitter.cpp",
    "MinidumpYAML.cpp",
    "ObjectYAML.cpp",
    "OffloadEmitter.cpp",
    "OffloadYAML.cpp",
    "WasmEmitter.cpp",
    "WasmYAML.cpp",
    "XCOFFEmitter.cpp",
    "XCOFFYAML.cpp",
    "YAML.cpp",
    "yaml2obj.cpp",
  ]
}
