import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("DWARFLinkerParallelTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/DWARFLinker/Parallel",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "DWARFLinkerTest.cpp",
    "StringPoolTest.cpp",
  ]
}
