import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("ObjectTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/ObjectYAML",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "ArchiveTest.cpp",
    "COFFObjectFileTest.cpp",
    "DXContainerTest.cpp",
    "ELFObjectFileTest.cpp",
    "ELFTest.cpp",
    "ELFTypesTest.cpp",
    "GOFFObjectFileTest.cpp",
    "MinidumpTest.cpp",
    "ObjectFileTest.cpp",
    "OffloadingTest.cpp",
    "SymbolSizeTest.cpp",
    "SymbolicFileTest.cpp",
    "XCOFFObjectFileTest.cpp",
  ]
}
