import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/gn/build/write_vcsrevision.gni")

config("write_vcsrevision_config") {
  # To pick up the generated inc file.
  include_dirs = [ target_gen_dir ]
  visibility = [ ":write_vcsversion" ]
}

write_vcsrevision("write_vcsversion") {
  visibility = [ ":Common" ]
  header = "$target_gen_dir/VCSVersion.inc"
  names = [ "LLD" ]
  public_configs = [ ":write_vcsrevision_config" ]
}

llvm_static_library("Common") {
  output_name = "lldCommon"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lld_code" ]
  public_deps = [
    # public_dep because public header Version.h includes generated Version.inc.
    "${llvm_root_dir}lld/include/lld/Common:version",
  ]
  deps = [
    ":write_vcsversion",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/Demangle",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "Args.cpp",
    "CommonLinkerContext.cpp",
    "DWARF.cpp",
    "DriverDispatcher.cpp",
    "ErrorHandler.cpp",
    "Filesystem.cpp",
    "Memory.cpp",
    "Reproduce.cpp",
    "Strings.cpp",
    "TargetOptionsCommandFlags.cpp",
    "Timer.cpp",
    "Version.cpp",
  ]
}
