import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/lib/Target/targets.gni")
import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("LLVMMCATests") {
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MCA",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  if (llvm_build_X86) {
    deps += [ "X86" ]
  }

  sources = [ "MCATestBase.cpp" ]

  # FIXME: Why is this so complicated in the cmake file?
  mca_views_sources = [ "SummaryView.cpp" ]
  foreach(s, mca_views_sources) {
    sources += [ "${llvm_root_dir}llvm/tools/llvm-mca/Views/" + s ]
  }
  include_dirs = [ "${llvm_root_dir}llvm/tools/llvm-mca" ]
}
