import("//build_overrides/llvm.gni")

llvm_static_library("LineEditor") {
  output_name = "LLVMLineEditor"
  deps = [
    "${llvm_root_dir}llvm/include/llvm/Config:config",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/utils/gn/build/libs/edit",
  ]

  sources = [ "LineEditor.cpp" ]
}
