import("//build_overrides/llvm.gni")

llvm_executable("lldb-tblgen") {
  deps = [
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TableGen",
  ]
  sources = [
    "LLDBOptionDefEmitter.cpp",
    "LLDBPropertyDefEmitter.cpp",
    "LLDBTableGen.cpp",
    "LLDBTableGenUtils.cpp",
  ]
}
