import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("OrcJITTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Debugging",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Shared",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/RuntimeDyld",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:NativeTarget",
    "${llvm_root_dir}llvm/lib/TargetParser",
    "${llvm_root_dir}llvm/lib/Testing/Support",
  ]
  sources = [
    "CoreAPIsTest.cpp",
    "EPCGenericJITLinkMemoryManagerTest.cpp",
    "EPCGenericMemoryAccessTest.cpp",
    "ExecutionSessionWrapperFunctionCallsTest.cpp",
    "ExecutorAddressTest.cpp",
    "IndirectionUtilsTest.cpp",
    "JITLinkRedirectionManagerTest.cpp",
    "JITTargetMachineBuilderTest.cpp",
    "LazyCallThroughAndReexportsTest.cpp",
    "LookupAndRecordAddrsTest.cpp",
    "MachOPlatformTest.cpp",
    "MapperJITLinkMemoryManagerTest.cpp",
    "MemoryFlagsTest.cpp",
    "MemoryMapperTest.cpp",
    "ObjectFormatsTest.cpp",
    "ObjectLinkingLayerTest.cpp",
    "OrcCAPITest.cpp",
    "OrcTestCommon.cpp",
    "RTDyldObjectLinkingLayerTest.cpp",
    "ReOptimizeLayerTest.cpp",
    "ResourceTrackerTest.cpp",
    "SharedMemoryMapperTest.cpp",
    "SimpleExecutorMemoryManagerTest.cpp",
    "SimplePackedSerializationTest.cpp",
    "SymbolStringPoolTest.cpp",
    "TaskDispatchTest.cpp",
    "ThreadSafeModuleTest.cpp",
    "WrapperFunctionUtilsTest.cpp",
  ]

  if (host_os != "mac" && host_os != "win") {
    # Corresponds to export_executable_symbols() in cmake.
    ldflags = [ "-rdynamic" ]
  }
}
