import("//build_overrides/llvm.gni")

llvm_executable("lldb-test") {
  configs += [
    "${llvm_root_dir}llvm/utils/gn/build:clang_code",
    "${llvm_root_dir}llvm/utils/gn/build:lldb_code",
  ]
  deps = [
    "${llvm_root_dir}lldb/source/Breakpoint",
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/DataFormatters",
    "${llvm_root_dir}lldb/source/Expression",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Initialization",
    "${llvm_root_dir}lldb/source/Interpreter",
    "${llvm_root_dir}lldb/source/Plugins:LldbAllPlugins",
    "${llvm_root_dir}lldb/source/Symbol",
    "${llvm_root_dir}lldb/source/Target",
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}lldb/source/Version",
    "${llvm_root_dir}llvm/lib/Support",
  ]

  # XXX commment
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [
    "FormatUtil.cpp",
    "SystemInitializerTest.cpp",
    "lldb-test.cpp",
  ]
}
