import("//build_overrides/llvm.gni")

llvm_static_library("CGData") {
  output_name = "LLVMCGData"
  deps = [
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "CodeGenData.cpp",
    "CodeGenDataReader.cpp",
    "CodeGenDataWriter.cpp",
    "OutlinedHashTree.cpp",
    "OutlinedHashTreeRecord.cpp",
  ]
}
