import("//build_overrides/llvm.gni")

llvm_static_library("plugin") {
  output_name = "clangIncludeFixerPlugin"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang-tools-extra/clang-include-fixer",
    "${llvm_root_dir}clang/lib/AST",
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Frontend",
    "${llvm_root_dir}clang/lib/Parse",
    "${llvm_root_dir}clang/lib/Sema",
    "${llvm_root_dir}clang/lib/Tooling",
    "${llvm_root_dir}llvm/utils/gn/build/libs/pthread",
  ]

  sources = [ "IncludeFixerPlugin.cpp" ]
}
