import("//build_overrides/llvm.gni")

llvm_static_library("InterfaceStub") {
  output_name = "LLVMInterfaceStub"
  deps = [
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]

  sources = [
    "ELFObjHandler.cpp",
    "IFSHandler.cpp",
    "IFSStub.cpp",
  ]
}
