import("//build_overrides/llvm.gni")

llvm_static_library("AsmParser") {
  output_name = "LLVMAsmParser"
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "LLLexer.cpp",
    "LLParser.cpp",
    "Parser.cpp",
  ]
}
