import("//build_overrides/llvm.gni")

llvm_static_library("Core") {
  output_name = "clangToolingCore"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:clang_code" ]
  deps = [
    "${llvm_root_dir}clang/lib/Basic",
    "${llvm_root_dir}clang/lib/Lex",
    "${llvm_root_dir}clang/lib/Rewrite",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "Diagnostic.cpp",
    "Replacement.cpp",
  ]
}
