import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("MCTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCDisassembler",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "Disassembler.cpp",
    "DwarfLineTableHeaders.cpp",
    "DwarfLineTables.cpp",
    "MCDisassemblerTest.cpp",
    "MCInstPrinter.cpp",
    "StringTableBuilderTest.cpp",
    "TargetRegistry.cpp",
  ]
}
