import("//build_overrides/llvm.gni")

llvm_static_library("PECOFF") {
  output_name = "lldbPluginSymbolVendorPECOFF"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Core",
    "${llvm_root_dir}lldb/source/Host",
    "${llvm_root_dir}lldb/source/Plugins/ObjectFile/PECOFF",
    "${llvm_root_dir}lldb/source/Symbol",
  ]

  # Reaches into Plugins/ObjectFile/PECOFF.
  include_dirs = [ "${llvm_root_dir}lldb/source" ]
  sources = [ "SymbolVendorPECOFF.cpp" ]
}
