import("//build_overrides/llvm.gni")

import("${llvm_root_dir}llvm/utils/TableGen/tablegen.gni")

tablegen("Options") {
  visibility = [ ":LibDriver" ]
  args = [ "-gen-opt-parser-defs" ]
}

llvm_static_library("LibDriver") {
  output_name = "LLVMLibDriver"
  deps = [
    ":Options",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Option",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [ "LibDriver.cpp" ]
}
