import("//build_overrides/llvm.gni")

llvm_static_library("AsmPrinter") {
  output_name = "LLVMAsmPrinter"
  deps = [
    "${llvm_root_dir}llvm/lib/Analysis",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/DebugInfo/CodeView",
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/DebugInfo/MSF",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/MC/MCParser",
    "${llvm_root_dir}llvm/lib/Remarks",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "AIXException.cpp",
    "ARMException.cpp",
    "AccelTable.cpp",
    "AddressPool.cpp",
    "AsmPrinter.cpp",
    "AsmPrinterDwarf.cpp",
    "AsmPrinterInlineAsm.cpp",
    "CodeViewDebug.cpp",
    "DIE.cpp",
    "DIEHash.cpp",
    "DbgEntityHistoryCalculator.cpp",
    "DebugHandlerBase.cpp",
    "DebugLocStream.cpp",
    "DwarfCFIException.cpp",
    "DwarfCompileUnit.cpp",
    "DwarfDebug.cpp",
    "DwarfExpression.cpp",
    "DwarfFile.cpp",
    "DwarfStringPool.cpp",
    "DwarfUnit.cpp",
    "EHStreamer.cpp",
    "ErlangGCPrinter.cpp",
    "OcamlGCPrinter.cpp",
    "PseudoProbePrinter.cpp",
    "WasmException.cpp",
    "WinCFGuard.cpp",
    "WinException.cpp",
  ]
}
