import("//build_overrides/llvm.gni")

llvm_static_library("MIRParser") {
  output_name = "LLVMMIRParser"
  deps = [
    "${llvm_root_dir}llvm/lib/AsmParser",
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/CodeGen",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target",
  ]
  sources = [
    "MILexer.cpp",
    "MIParser.cpp",
    "MIRParser.cpp",
  ]
}
