import("//build_overrides/llvm.gni")

llvm_static_library("Debugging") {
  output_name = "LLVMOrcDebugging"
  deps = [
    "${llvm_root_dir}llvm/lib/DebugInfo/DWARF",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Shared",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "DebugInfoSupport.cpp",
    "DebuggerSupport.cpp",
    "DebuggerSupportPlugin.cpp",
    "LLJITUtilsCBindings.cpp",
    "PerfSupportPlugin.cpp",
    "VTuneSupportPlugin.cpp",
  ]
  if (current_os == "linux") {
    libs = [ "rt" ]
  }
}
