import("//build_overrides/llvm.gni")

llvm_static_library("Interfaces") {
  output_name = "lldbInterpreterInterfaces"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [ "ScriptedInterfaceUsages.cpp" ]
}
