import("//build_overrides/llvm.gni")

llvm_executable("llvm-jitlink") {
  deps = [
    "${llvm_root_dir}llvm/lib/BinaryFormat",
    "${llvm_root_dir}llvm/lib/ExecutionEngine",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/JITLink",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/Orc/Debugging",
    "${llvm_root_dir}llvm/lib/ExecutionEngine/RuntimeDyld",
    "${llvm_root_dir}llvm/lib/MC",
    "${llvm_root_dir}llvm/lib/Object",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/Target:TargetsToBuild",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  sources = [
    "llvm-jitlink-coff.cpp",
    "llvm-jitlink-elf.cpp",
    "llvm-jitlink-macho.cpp",
    "llvm-jitlink-statistics.cpp",
    "llvm-jitlink.cpp",
  ]
  if (host_os != "mac" && host_os != "win") {
    # Corresponds to export_executable_symbols() in cmake.
    ldflags = [ "-rdynamic" ]
  }
}
