import("//build_overrides/llvm.gni")

import("${llvm_root_dir}third-party/unittest/unittest.gni")

unittest("BitcodeTests") {
  deps = [
    "${llvm_root_dir}llvm/lib/AsmParser",
    "${llvm_root_dir}llvm/lib/Bitcode/Reader",
    "${llvm_root_dir}llvm/lib/Bitcode/Writer",
    "${llvm_root_dir}llvm/lib/IR",
    "${llvm_root_dir}llvm/lib/Support",
  ]
  sources = [
    "BitReaderTest.cpp",
    "DataLayoutUpgradeTest.cpp",
  ]
}
