import("//build_overrides/llvm.gni")

llvm_static_library("objcxx") {
  output_name = "lldbHostMacOSXObjCXX"
  configs += [ "${llvm_root_dir}llvm/utils/gn/build:lldb_code" ]
  deps = [
    "${llvm_root_dir}lldb/source/Utility",
    "${llvm_root_dir}llvm/lib/Support",
    "${llvm_root_dir}llvm/lib/TargetParser",
  ]
  include_dirs = [ "${llvm_root_dir}lldb/source" ]  # Includes internal headers from Utility.
  cflags_objcc = [ "-fno-objc-exceptions" ]
  sources = [
    "Host.mm",
    "HostInfoMacOSX.mm",
    "HostThreadMacOSX.mm",
  ]
  frameworks = [
    "Foundation.framework",
    "CoreServices.framework",
    "Security.framework",
  ]
}
